CREATE TABLE [prod].[KladrOzonMapping](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Region] [nvarchar](128) NOT NULL,
	[City] [nvarchar](128) NOT NULL,
	[KLADR] [nvarchar](32) NOT NULL,	
 CONSTRAINT [PK_KladrOzonMapping] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

