print 'Чистим'
DELETE FROM [prod].[ProductCategoriesPermissions]
DELETE FROM [prod].[PartnerProductCategoryLinks]
-- NOTE: Удаляем
DELETE FROM [prod].[ProductCategories] WHERE [Id] != 100

DECLARE @User nvarchar(50) = 'SCRIPT'

DECLARE @PartnerId [int] --= 1

SET NOCOUNT OFF

SET @PartnerId = 1

-- Часть категорий заливаем 1-к-1 от тестового парнера
print 'Часть категорий заливаем 1-к-1 от тестового парнера'
SET NOCOUNT ON
SET IDENTITY_INSERT [prod].[ProductCategories] ON
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (287, 0, NULL, N'Акции', N'/Акции/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D500 AS DateTime), NULL, 0, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (288, 0, 486, N'ЕГЭ. Экзамены', N'/Обучающие программы/ЕГЭ. Экзамены/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D501 AS DateTime), NULL, 1, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (293, 0, 287, N'Акция!!Горящие цены!', N'/Акции/Акция!!Горящие цены!/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D502 AS DateTime), NULL, 6, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (294, 0, 287, N'Акция "школьные каникулы"', N'/Акции/Акция "школьные каникулы"/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D502 AS DateTime), NULL, 7, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (295, 0, 287, N'Выгодные комплекты!', N'/Акции/Выгодные комплекты!/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D502 AS DateTime), NULL, 8, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (296, 0, 288, N'Экзамены (Школа. Институт)', N'/Обучающие программы/ЕГЭ. Экзамены/Экзамены (Школа. Институт)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D502 AS DateTime), NULL, 9, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (297, 0, 287, N'АКЦИЯ Guitar Hero скидки 50%', N'/Акции/АКЦИЯ Guitar Hero скидки 50%/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D503 AS DateTime), NULL, 10, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (317, 0, 287, N'АКЦИЯ DJ Hero скидки 70%', N'/Акции/АКЦИЯ DJ Hero скидки 70%/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D50D AS DateTime), NULL, 30, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (318, 0, 293, N'Игры для PS3', N'/Акции/Акция!!Горящие цены!/Игры для PS3/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D50D AS DateTime), NULL, 31, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (319, 0, 293, N'Игры для XBox360', N'/Акции/Акция!!Горящие цены!/Игры для XBox360/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D50E AS DateTime), NULL, 32, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (320, 0, 293, N'Игры для PC', N'/Акции/Акция!!Горящие цены!/Игры для PC/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D50E AS DateTime), NULL, 33, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (321, 0, 293, N'Игры для PSP и PS Vita', N'/Акции/Акция!!Горящие цены!/Игры для PSP и PS Vita/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D50F AS DateTime), NULL, 34, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (322, 0, 293, N'Игры для 3DS', N'/Акции/Акция!!Горящие цены!/Игры для 3DS/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D510 AS DateTime), NULL, 35, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (323, 0, 293, N'Игровые приставки', N'/Акции/Акция!!Горящие цены!/Игровые приставки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D511 AS DateTime), NULL, 36, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (324, 0, 294, N'Видеоигры', N'/Акции/Акция "школьные каникулы"/Видеоигры/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D511 AS DateTime), NULL, 37, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (325, 0, 294, N'Игровые приставки', N'/Акции/Акция "школьные каникулы"/Игровые приставки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D512 AS DateTime), NULL, 38, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (326, 0, 294, N'Компьютерные игры', N'/Акции/Акция "школьные каникулы"/Компьютерные игры/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D513 AS DateTime), NULL, 39, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (327, 0, 287, N'Скоро в продаже!', N'/Акции/Скоро в продаже!/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D514 AS DateTime), NULL, 40, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (338, 0, NULL, N'Игровые приставки', N'/Игровые приставки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D77D AS DateTime), NULL, 0, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (339, 0, 338, N'Microsoft Xbox 360', N'/Игровые приставки/Microsoft Xbox 360/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D77E AS DateTime), NULL, 1, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (340, 0, 338, N'Sony PlayStation 2', N'/Игровые приставки/Sony PlayStation 2/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D780 AS DateTime), NULL, 2, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (341, 0, 338, N'Sony PlayStation 3', N'/Игровые приставки/Sony PlayStation 3/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D781 AS DateTime), NULL, 3, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (342, 0, 338, N'Sony Playstation Portable (PSP)', N'/Игровые приставки/Sony Playstation Portable (PSP)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D782 AS DateTime), NULL, 4, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (343, 0, 338, N'Nintendo Wii', N'/Игровые приставки/Nintendo Wii/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D783 AS DateTime), NULL, 5, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (344, 0, 338, N'Nintendo DS/DSi', N'/Игровые приставки/Nintendo DS/DSi/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D784 AS DateTime), NULL, 6, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (345, 0, 342, N'Аксессуары', N'/Игровые приставки/Sony Playstation Portable (PSP)/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D785 AS DateTime), NULL, 7, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (346, 0, 338, N'SEGA (16 bit)', N'/Игровые приставки/SEGA (16 bit)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D787 AS DateTime), NULL, 8, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (347, 0, 342, N'Виниловые наклейки', N'/Игровые приставки/Sony Playstation Portable (PSP)/Виниловые наклейки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D788 AS DateTime), NULL, 9, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (348, 0, 338, N'Game Boy Advance', N'/Игровые приставки/Game Boy Advance/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D789 AS DateTime), NULL, 10, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (349, 0, 338, N'Emote', N'/Игровые приставки/Emote/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D78A AS DateTime), NULL, 11, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (350, 0, 338, N'Comfy', N'/Игровые приставки/Comfy/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D78C AS DateTime), NULL, 12, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (351, 0, NULL, N'Энциклопедии и справочники', N'/Обучающие программы/Энциклопедии и справочники/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D78D AS DateTime), NULL, 13, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (352, 0, 351, N'Искусство', N'/Обучающие программы/Энциклопедии и справочники/Искусство/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D78E AS DateTime), NULL, 14, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (353, 0, 351, N'Атласы. Путеводители. Навигационные системы', N'/Обучающие программы/Энциклопедии и справочники/Атласы. Путеводители. Навигационные системы/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D790 AS DateTime), NULL, 15, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (354, 0, 351, N'Для женщин: Красота и здоровье, домоводство', N'/Обучающие программы/Энциклопедии и справочники/Для женщин: Красота и здоровье, домоводство/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D791 AS DateTime), NULL, 16, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (355, 0, 351, N'Дизайн и ремонт дома (квартиры)', N'/Обучающие программы/Энциклопедии и справочники/Дизайн и ремонт дома (квартиры)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D792 AS DateTime), NULL, 17, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (356, 0, 351, N'Автомобили. Мотоциклы. Скутеры', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D793 AS DateTime), NULL, 18, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (357, 0, 356, N'Ремонт. ТО', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/Ремонт. ТО/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D795 AS DateTime), NULL, 19, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (365, 0, 338, N'DVTech', N'/Игровые приставки/DVTech/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7A1 AS DateTime), NULL, 27, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (366, 0, 338, N'Sony PlayStation Vita', N'/Игровые приставки/Sony PlayStation Vita/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7A2 AS DateTime), NULL, 28, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (367, 0, 338, N'Nintendo 3DS', N'/Игровые приставки/Nintendo 3DS/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7A4 AS DateTime), NULL, 29, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (368, 0, 339, N'Аксессуары', N'/Игровые приставки/Microsoft Xbox 360/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7A5 AS DateTime), NULL, 30, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (369, 0, 343, N'Игровые консоли (приставки)', N'/Игровые приставки/Nintendo Wii/Игровые консоли (приставки)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7A7 AS DateTime), NULL, 31, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (370, 0, 342, N'Игровые консоли', N'/Игровые приставки/Sony Playstation Portable (PSP)/Игровые консоли/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7A8 AS DateTime), NULL, 32, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (371, 0, 344, N'Игровые консоли', N'/Игровые приставки/Nintendo DS/DSi/Игровые консоли/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7AA AS DateTime), NULL, 33, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (372, 0, 344, N'Аксессуары', N'/Игровые приставки/Nintendo DS/DSi/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7AC AS DateTime), NULL, 34, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (373, 0, 343, N'Аксессуары', N'/Игровые приставки/Nintendo Wii/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7AD AS DateTime), NULL, 35, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (374, 0, 341, N'Аксессуары', N'/Игровые приставки/Sony PlayStation 3/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7AF AS DateTime), NULL, 36, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (375, 0, 341, N'Игровые консоли (приставки)', N'/Игровые приставки/Sony PlayStation 3/Игровые консоли (приставки)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7B1 AS DateTime), NULL, 37, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (376, 0, 338, N'Dendy (8 bit)', N'/Игровые приставки/Dendy (8 bit)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7B3 AS DateTime), NULL, 38, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (377, 0, 340, N'Аксессуары', N'/Игровые приставки/Sony PlayStation 2/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7B4 AS DateTime), NULL, 39, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (378, 0, 340, N'Игровые консоли (приставки)', N'/Игровые приставки/Sony PlayStation 2/Игровые консоли (приставки)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7B7 AS DateTime), NULL, 40, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (379, 0, 339, N'Виниловые наклейки', N'/Игровые приставки/Microsoft Xbox 360/Виниловые наклейки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7B8 AS DateTime), NULL, 41, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (380, 0, 343, N'Виниловые наклейки', N'/Игровые приставки/Nintendo Wii/Виниловые наклейки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7BA AS DateTime), NULL, 42, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (381, 0, 340, N'Виниловые наклейки', N'/Игровые приставки/Sony PlayStation 2/Виниловые наклейки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7BC AS DateTime), NULL, 43, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (382, 0, 341, N'Виниловые наклейки', N'/Игровые приставки/Sony PlayStation 3/Виниловые наклейки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7BE AS DateTime), NULL, 44, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (383, 0, 347, N'Для моделей серии 2000', N'/Игровые приставки/Sony Playstation Portable (PSP)/Виниловые наклейки/Для моделей серии 2000/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7C0 AS DateTime), NULL, 45, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (384, 0, 347, N'Для моделей серии 3000', N'/Игровые приставки/Sony Playstation Portable (PSP)/Виниловые наклейки/Для моделей серии 3000/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7C2 AS DateTime), NULL, 46, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (385, 0, 345, N'PSP Go', N'/Игровые приставки/Sony Playstation Portable (PSP)/Аксессуары/PSP Go/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7C4 AS DateTime), NULL, 47, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (386, 0, 345, N'PSP 2000/3000', N'/Игровые приставки/Sony Playstation Portable (PSP)/Аксессуары/PSP 2000/3000/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7C6 AS DateTime), NULL, 48, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (387, 0, 351, N'Медицина. Здоровье', N'/Обучающие программы/Энциклопедии и справочники/Медицина. Здоровье/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7C8 AS DateTime), NULL, 49, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (388, 0, 351, N'Кулинария. Рецепты', N'/Обучающие программы/Энциклопедии и справочники/Кулинария. Рецепты/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7CA AS DateTime), NULL, 50, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (389, 0, 351, N'Известные личности', N'/Обучающие программы/Энциклопедии и справочники/Известные личности/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7CC AS DateTime), NULL, 51, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (390, 0, 351, N'Природа', N'/Обучающие программы/Энциклопедии и справочники/Природа/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7CE AS DateTime), NULL, 52, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (391, 0, 351, N'Военная история. Оружие', N'/Обучающие программы/Энциклопедии и справочники/Военная история. Оружие/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7D0 AS DateTime), NULL, 53, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (392, 0, 351, N'Универсальные', N'/Обучающие программы/Энциклопедии и справочники/Универсальные/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7D2 AS DateTime), NULL, 54, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (393, 0, 351, N'Коллекции изображений / Cliparts', N'/Обучающие программы/Энциклопедии и справочники/Коллекции изображений / Cliparts/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7D5 AS DateTime), NULL, 55, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (394, 0, 351, N'Психология', N'/Обучающие программы/Энциклопедии и справочники/Психология/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7D7 AS DateTime), NULL, 56, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (395, 0, 351, N'Ландшафтный дизайн. Цветы', N'/Обучающие программы/Энциклопедии и справочники/Ландшафтный дизайн. Цветы/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7D9 AS DateTime), NULL, 57, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (396, 0, 351, N'Животные. Птицы. Насекомые', N'/Обучающие программы/Энциклопедии и справочники/Животные. Птицы. Насекомые/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7DB AS DateTime), NULL, 58, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (397, 0, 351, N'Наука. Техника', N'/Обучающие программы/Энциклопедии и справочники/Наука. Техника/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7DE AS DateTime), NULL, 59, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (398, 0, 351, N'Спорт', N'/Обучающие программы/Энциклопедии и справочники/Спорт/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7E0 AS DateTime), NULL, 60, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (399, 0, 351, N'Половое воспитание. Секс.', N'/Обучающие программы/Энциклопедии и справочники/Половое воспитание. Секс./', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7E2 AS DateTime), NULL, 61, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (400, 0, 351, N'Фитнесс. Танцы', N'/Обучающие программы/Энциклопедии и справочники/Фитнесс. Танцы/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7E4 AS DateTime), NULL, 62, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (401, 0, 351, N'Религия', N'/Обучающие программы/Энциклопедии и справочники/Религия/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7E7 AS DateTime), NULL, 63, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (402, 0, 351, N'Детские энциклопедии', N'/Обучающие программы/Энциклопедии и справочники/Детские энциклопедии/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7E9 AS DateTime), NULL, 64, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (403, 0, 351, N'Астрология. Магия. Сонники. Карты таро', N'/Обучающие программы/Энциклопедии и справочники/Астрология. Магия. Сонники. Карты таро/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7EB AS DateTime), NULL, 65, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (404, 0, 351, N'Домашняя бухгалтерия (финансы)', N'/Обучающие программы/Энциклопедии и справочники/Домашняя бухгалтерия (финансы)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7ED AS DateTime), NULL, 66, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (405, 0, 351, N'Досуг. Хобби', N'/Обучающие программы/Энциклопедии и справочники/Досуг. Хобби/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7F0 AS DateTime), NULL, 67, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (406, 0, 351, N'Музыка', N'/Обучающие программы/Энциклопедии и справочники/Музыка/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7F2 AS DateTime), NULL, 68, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (407, 0, 351, N'Гид покупателя', N'/Обучающие программы/Энциклопедии и справочники/Гид покупателя/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7F4 AS DateTime), NULL, 69, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (408, 0, 351, N'Фото. Видео', N'/Обучающие программы/Энциклопедии и справочники/Фото. Видео/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7F6 AS DateTime), NULL, 70, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (409, 0, 356, N'Энциклопедия автомобилиста. Право. Безопасность', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/Энциклопедия автомобилиста. Право. Безопасность/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7F9 AS DateTime), NULL, 71, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (410, 0, 357, N'Иномарки', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/Ремонт. ТО/Иномарки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7FB AS DateTime), NULL, 72, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (411, 0, 355, N'Виртуальный архитектор', N'/Обучающие программы/Энциклопедии и справочники/Дизайн и ремонт дома (квартиры)/Виртуальный архитектор/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D7FD AS DateTime), NULL, 73, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (412, 0, 355, N'Советы по ремонту', N'/Обучающие программы/Энциклопедии и справочники/Дизайн и ремонт дома (квартиры)/Советы по ремонту/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D800 AS DateTime), NULL, 74, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (413, 0, 354, N'Беременность. Ваш малыш', N'/Обучающие программы/Энциклопедии и справочники/Для женщин: Красота и здоровье, домоводство/Беременность. Ваш малыш/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D802 AS DateTime), NULL, 75, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (414, 0, 354, N'Мода. Прически. Макияж. Маникюр', N'/Обучающие программы/Энциклопедии и справочники/Для женщин: Красота и здоровье, домоводство/Мода. Прически. Макияж. Маникюр/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D805 AS DateTime), NULL, 76, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (415, 0, 354, N'Выкройки. Рукоделие', N'/Обучающие программы/Энциклопедии и справочники/Для женщин: Красота и здоровье, домоводство/Выкройки. Рукоделие/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D809 AS DateTime), NULL, 77, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (416, 0, 354, N'Свадьба', N'/Обучающие программы/Энциклопедии и справочники/Для женщин: Красота и здоровье, домоводство/Свадьба/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D80B AS DateTime), NULL, 78, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (417, 0, 354, N'Диета. Похудение', N'/Обучающие программы/Энциклопедии и справочники/Для женщин: Красота и здоровье, домоводство/Диета. Похудение/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D80E AS DateTime), NULL, 79, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (418, 0, 353, N'Географические карты', N'/Обучающие программы/Энциклопедии и справочники/Атласы. Путеводители. Навигационные системы/Географические карты/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D816 AS DateTime), NULL, 80, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (419, 0, 353, N'Справочники', N'/Обучающие программы/Энциклопедии и справочники/Атласы. Путеводители. Навигационные системы/Справочники/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D819 AS DateTime), NULL, 81, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (420, 0, 352, N'Мировое искусство', N'/Обучающие программы/Энциклопедии и справочники/Искусство/Мировое искусство/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D81E AS DateTime), NULL, 82, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (421, 0, 352, N'Живопись. Рисунок. Гравюра', N'/Обучающие программы/Энциклопедии и справочники/Искусство/Живопись. Рисунок. Гравюра/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D823 AS DateTime), NULL, 83, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (422, 0, 352, N'Литература', N'/Обучающие программы/Энциклопедии и справочники/Искусство/Литература/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D82F AS DateTime), NULL, 84, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (466, 0, 338, N'Магистр', N'/Игровые приставки/Магистр/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8BD AS DateTime), NULL, 128, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (467, 0, 338, N'EXEQ', N'/Игровые приставки/EXEQ/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8C1 AS DateTime), NULL, 129, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (468, 0, 365, N'Аксессуары DVTech', N'/Игровые приставки/DVTech/Аксессуары DVTech/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8C5 AS DateTime), NULL, 130, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (469, 0, 365, N'Игровые консоли DVTech', N'/Игровые приставки/DVTech/Игровые консоли DVTech/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8D2 AS DateTime), NULL, 131, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (470, 0, 338, N'Func', N'/Игровые приставки/Func/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8D6 AS DateTime), NULL, 132, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (471, 0, 338, N'MegaDrive', N'/Игровые приставки/MegaDrive/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8D9 AS DateTime), NULL, 133, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (472, 0, 338, N'DENN', N'/Игровые приставки/DENN/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8DD AS DateTime), NULL, 134, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (473, 0, 346, N'Игровые консоли', N'/Игровые приставки/SEGA (16 bit)/Игровые консоли/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8E0 AS DateTime), NULL, 135, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (474, 0, 346, N'Аксессуары', N'/Игровые приставки/SEGA (16 bit)/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8E4 AS DateTime), NULL, 136, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (475, 0, 350, N'Игровые консоли', N'/Игровые приставки/Comfy/Игровые консоли/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8E8 AS DateTime), NULL, 137, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (476, 0, 349, N'Игровые консоли', N'/Игровые приставки/Emote/Игровые консоли/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8EC AS DateTime), NULL, 138, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (477, 0, 349, N'Аксессуары', N'/Игровые приставки/Emote/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8EF AS DateTime), NULL, 139, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (478, 0, 348, N'Аксессуары', N'/Игровые приставки/Game Boy Advance/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8F3 AS DateTime), NULL, 140, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (479, 0, 366, N'Аксессуары', N'/Игровые приставки/Sony PlayStation Vita/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8F7 AS DateTime), NULL, 141, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (480, 0, 367, N'Игровые консоли', N'/Игровые приставки/Nintendo 3DS/Игровые консоли/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8FB AS DateTime), NULL, 142, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (481, 0, 367, N'Аксессуары', N'/Игровые приставки/Nintendo 3DS/Аксессуары/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D8FE AS DateTime), NULL, 143, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (483, 0, 338, N'PGP AIO', N'/Игровые приставки/PGP AIO/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D906 AS DateTime), NULL, 145, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (484, 0, 338, N'Turbo Games', N'/Игровые приставки/Turbo Games/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D90A AS DateTime), NULL, 146, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (485, 0, 339, N'Игровые консоли (приставки)', N'/Игровые приставки/Microsoft Xbox 360/Игровые консоли (приставки)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8D90D AS DateTime), NULL, 147, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (486, 0, NULL, N'Обучающие программы', N'/Обучающие программы/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA2B AS DateTime), NULL, 0, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (487, 0, 486, N'Иностранные языки', N'/Обучающие программы/Иностранные языки/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA2F AS DateTime), NULL, 1, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (488, 0, 486, N'Для школы и института', N'/Обучающие программы/Для школы и института/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA33 AS DateTime), NULL, 2, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (489, 0, 486, N'Для бизнеса', N'/Обучающие программы/Для бизнеса/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA37 AS DateTime), NULL, 3, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (490, 0, 487, N'Иностранные языки для детей', N'/Обучающие программы/Иностранные языки/Иностранные языки для детей/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA3B AS DateTime), NULL, 4, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (491, 0, 488, N'История', N'/Обучающие программы/Для школы и института/История/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA3F AS DateTime), NULL, 5, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (492, 0, 488, N'Математика (алгебра, геометрия)', N'/Обучающие программы/Для школы и института/Математика (алгебра, геометрия)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA43 AS DateTime), NULL, 6, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (493, 0, 488, N'Русский язык', N'/Обучающие программы/Для школы и института/Русский язык/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA48 AS DateTime), NULL, 7, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (494, 0, 488, N'География', N'/Обучающие программы/Для школы и института/География/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA4B AS DateTime), NULL, 8, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (495, 0, 488, N'Искусство и культура', N'/Обучающие программы/Для школы и института/Искусство и культура/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA50 AS DateTime), NULL, 9, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (496, 0, 488, N'Развитие интеллектуальных способностей', N'/Обучающие программы/Для школы и института/Развитие интеллектуальных способностей/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA54 AS DateTime), NULL, 10, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (497, 0, 488, N'Рефераты. Дипломы. Курсовые', N'/Обучающие программы/Для школы и института/Рефераты. Дипломы. Курсовые/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA58 AS DateTime), NULL, 11, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (498, 0, 488, N'ЕГЭ (Единый Государственный Экзамен)', N'/Обучающие программы/Для школы и института/ЕГЭ (Единый Государственный Экзамен)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA5D AS DateTime), NULL, 12, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (499, 0, 488, N'Психология. НЛП', N'/Обучающие программы/Для школы и института/Психология. НЛП/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA61 AS DateTime), NULL, 13, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (500, 0, 488, N'ПДД (Правила Дорожного Движения)', N'/Обучающие программы/Для школы и института/ПДД (Правила Дорожного Движения)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA65 AS DateTime), NULL, 14, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (501, 0, 488, N'Шпаргалки, готовые домашние задания', N'/Обучающие программы/Для школы и института/Шпаргалки, готовые домашние задания/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA69 AS DateTime), NULL, 15, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (502, 0, 488, N'Музыка', N'/Обучающие программы/Для школы и института/Музыка/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA76 AS DateTime), NULL, 16, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (503, 0, 488, N'Экология', N'/Обучающие программы/Для школы и института/Экология/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA7D AS DateTime), NULL, 17, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (504, 0, 488, N'Физика', N'/Обучающие программы/Для школы и института/Физика/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA81 AS DateTime), NULL, 18, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (505, 0, 488, N'Химия', N'/Обучающие программы/Для школы и института/Химия/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA8A AS DateTime), NULL, 19, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (506, 0, 488, N'Биология', N'/Обучающие программы/Для школы и института/Биология/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA8E AS DateTime), NULL, 20, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (507, 0, 488, N'Астрономия', N'/Обучающие программы/Для школы и института/Астрономия/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA95 AS DateTime), NULL, 21, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (508, 0, 488, N'Медицина. Анатомия', N'/Обучающие программы/Для школы и института/Медицина. Анатомия/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DA9C AS DateTime), NULL, 22, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (509, 0, 488, N'ОБЖ (Основы Безопасности Жизнедеятельности)', N'/Обучающие программы/Для школы и института/ОБЖ (Основы Безопасности Жизнедеятельности)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAA0 AS DateTime), NULL, 23, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (510, 0, 488, N'Философия', N'/Обучающие программы/Для школы и института/Философия/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAA6 AS DateTime), NULL, 24, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (511, 0, 488, N'Социология', N'/Обучающие программы/Для школы и института/Социология/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAAA AS DateTime), NULL, 25, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (512, 0, 488, N'Экономика', N'/Обучающие программы/Для школы и института/Экономика/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAAF AS DateTime), NULL, 26, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (513, 0, 488, N'Культурология', N'/Обучающие программы/Для школы и института/Культурология/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAB3 AS DateTime), NULL, 27, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (514, 0, 488, N'Литература', N'/Обучающие программы/Для школы и института/Литература/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAB8 AS DateTime), NULL, 28, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (515, 0, 488, N'Обществознание', N'/Обучающие программы/Для школы и института/Обществознание/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DABD AS DateTime), NULL, 29, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (516, 0, 488, N'Политология', N'/Обучающие программы/Для школы и института/Политология/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAC2 AS DateTime), NULL, 30, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (517, 0, 488, N'Информатика', N'/Обучающие программы/Для школы и института/Информатика/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAC6 AS DateTime), NULL, 31, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (518, 0, 487, N'Немецкий', N'/Обучающие программы/Иностранные языки/Немецкий/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DACC AS DateTime), NULL, 32, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (519, 0, 487, N'Другие', N'/Обучающие программы/Иностранные языки/Другие/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAD0 AS DateTime), NULL, 33, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (520, 0, 487, N'Французский', N'/Обучающие программы/Иностранные языки/Французский/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAD5 AS DateTime), NULL, 34, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (521, 0, 487, N'Испанский', N'/Обучающие программы/Иностранные языки/Испанский/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAD9 AS DateTime), NULL, 35, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (522, 0, 487, N'Северная Европа и Прибалтика', N'/Обучающие программы/Иностранные языки/Северная Европа и Прибалтика/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DADE AS DateTime), NULL, 36, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (523, 0, 487, N'Чешский. Польский. Венгерский', N'/Обучающие программы/Иностранные языки/Чешский. Польский. Венгерский/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAE3 AS DateTime), NULL, 37, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (524, 0, 487, N'Японский. Китайский. Хинди', N'/Обучающие программы/Иностранные языки/Японский. Китайский. Хинди/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAE7 AS DateTime), NULL, 38, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (525, 0, 487, N'Английский', N'/Обучающие программы/Иностранные языки/Английский/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAEC AS DateTime), NULL, 39, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (526, 0, 490, N'Английский язык', N'/Обучающие программы/Иностранные языки/Иностранные языки для детей/Английский язык/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAF1 AS DateTime), NULL, 40, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (527, 0, 490, N'Немецкий язык', N'/Обучающие программы/Иностранные языки/Иностранные языки для детей/Немецкий язык/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAF6 AS DateTime), NULL, 41, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (528, 0, 351, N'Отраслевые справочники и базы данных', N'/Обучающие программы/Энциклопедии и справочники/Отраслевые справочники и базы данных/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAFA AS DateTime), NULL, 42, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (529, 0, 356, N'Вождение. ПДД', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/Вождение. ПДД/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DAFF AS DateTime), NULL, 43, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (530, 0, 356, N'Тюнинг', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/Тюнинг/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB04 AS DateTime), NULL, 44, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (531, 0, 357, N'Российские автомобили', N'/Обучающие программы/Энциклопедии и справочники/Автомобили. Мотоциклы. Скутеры/Ремонт. ТО/Российские автомобили/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB09 AS DateTime), NULL, 45, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (532, 0, 355, N'Дизайн интерьера', N'/Обучающие программы/Энциклопедии и справочники/Дизайн и ремонт дома (квартиры)/Дизайн интерьера/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB0E AS DateTime), NULL, 46, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (533, 0, 355, N'Готовые проекты домов/коттеджей', N'/Обучающие программы/Энциклопедии и справочники/Дизайн и ремонт дома (квартиры)/Готовые проекты домов/коттеджей/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB13 AS DateTime), NULL, 47, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (534, 0, 353, N'Путеводители', N'/Обучающие программы/Энциклопедии и справочники/Атласы. Путеводители. Навигационные системы/Путеводители/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB18 AS DateTime), NULL, 48, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (535, 0, 352, N'Музеи', N'/Обучающие программы/Энциклопедии и справочники/Искусство/Музеи/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB1D AS DateTime), NULL, 49, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (536, 0, 352, N'Архитектура. Скульптура', N'/Обучающие программы/Энциклопедии и справочники/Искусство/Архитектура. Скульптура/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB22 AS DateTime), NULL, 50, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (537, 0, 488, N'Труд', N'/Обучающие программы/Для школы и института/Труд/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB27 AS DateTime), NULL, 51, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (538, 0, 488, N'Окружающий мир', N'/Обучающие программы/Для школы и института/Окружающий мир/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB2C AS DateTime), NULL, 52, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (539, 0, 489, N'Юриспруденция. Право', N'/Обучающие программы/Для бизнеса/Юриспруденция. Право/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DB31 AS DateTime), NULL, 53, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (540, 0, 486, N'Компьютер и интернет', N'/Обучающие программы/Компьютер и интернет/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBCA AS DateTime), NULL, 0, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (541, 0, 486, N'Для детей', N'/Обучающие программы/Для детей/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBCF AS DateTime), NULL, 1, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (542, 0, 489, N'Предпринимательство. Организация коммерческой деятельности', N'/Обучающие программы/Для бизнеса/Предпринимательство. Организация коммерческой деятельности/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBD4 AS DateTime), NULL, 2, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (543, 0, 489, N'Бухгалтерский учёт. Налоги', N'/Обучающие программы/Для бизнеса/Бухгалтерский учёт. Налоги/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBDA AS DateTime), NULL, 3, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (544, 0, 489, N'Управление персоналом. HR', N'/Обучающие программы/Для бизнеса/Управление персоналом. HR/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBDF AS DateTime), NULL, 4, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (545, 0, 489, N'Управление школой (для педагогов и администрации)', N'/Обучающие программы/Для бизнеса/Управление школой (для педагогов и администрации)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBE4 AS DateTime), NULL, 5, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (546, 0, 489, N'Маркетинг. Реклама', N'/Обучающие программы/Для бизнеса/Маркетинг. Реклама/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBEA AS DateTime), NULL, 6, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (547, 0, 489, N'Финансы и кредит', N'/Обучающие программы/Для бизнеса/Финансы и кредит/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBEF AS DateTime), NULL, 7, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (548, 0, 489, N'Продажи', N'/Обучающие программы/Для бизнеса/Продажи/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBF4 AS DateTime), NULL, 8, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (549, 0, 541, N'ПДД (Правила Дорожного Движения) для детей', N'/Обучающие программы/Для детей/ПДД (Правила Дорожного Движения) для детей/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBFA AS DateTime), NULL, 9, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (550, 0, 541, N'Русский язык', N'/Обучающие программы/Для детей/Русский язык/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DBFF AS DateTime), NULL, 10, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (551, 0, 541, N'Математика', N'/Обучающие программы/Для детей/Математика/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC04 AS DateTime), NULL, 11, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (552, 0, 541, N'Искусcтво', N'/Обучающие программы/Для детей/Искусcтво/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC0A AS DateTime), NULL, 12, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (553, 0, 541, N'Компьютеры', N'/Обучающие программы/Для детей/Компьютеры/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC0F AS DateTime), NULL, 13, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (554, 0, 541, N'Логика. Внимание. Память', N'/Обучающие программы/Для детей/Логика. Внимание. Память/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC14 AS DateTime), NULL, 14, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (555, 0, 541, N'Рисование', N'/Обучающие программы/Для детей/Рисование/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC1A AS DateTime), NULL, 15, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (556, 0, 541, N'Естествознание', N'/Обучающие программы/Для детей/Естествознание/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC1F AS DateTime), NULL, 16, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (557, 0, 487, N'Итальянский', N'/Обучающие программы/Иностранные языки/Итальянский/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC25 AS DateTime), NULL, 17, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (558, 0, 487, N'Арабский. Турецкий. Иврит', N'/Обучающие программы/Иностранные языки/Арабский. Турецкий. Иврит/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC2A AS DateTime), NULL, 18, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (559, 0, 490, N'Французский язык', N'/Обучающие программы/Иностранные языки/Иностранные языки для детей/Французский язык/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC30 AS DateTime), NULL, 19, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (560, 0, 490, N'Испанский язык', N'/Обучающие программы/Иностранные языки/Иностранные языки для детей/Испанский язык/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC35 AS DateTime), NULL, 20, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (561, 0, 540, N'Энциклопедии пользователя ПК', N'/Обучающие программы/Компьютер и интернет/Энциклопедии пользователя ПК/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC3B AS DateTime), NULL, 21, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (562, 0, 540, N'3D графика, видео и анимация', N'/Обучающие программы/Компьютер и интернет/3D графика, видео и анимация/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC40 AS DateTime), NULL, 22, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (563, 0, 540, N'Графические редакторы. Дизайн. Верстка', N'/Обучающие программы/Компьютер и интернет/Графические редакторы. Дизайн. Верстка/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC46 AS DateTime), NULL, 23, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (564, 0, 540, N'Звук и музыка', N'/Обучающие программы/Компьютер и интернет/Звук и музыка/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC4C AS DateTime), NULL, 24, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (565, 0, 540, N'Компьютерные сети (Интернет). Сетевая безопасность. Web дизайн', N'/Обучающие программы/Компьютер и интернет/Компьютерные сети (Интернет). Сетевая безопасность. Web дизайн/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC51 AS DateTime), NULL, 25, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (566, 0, 540, N'Основы программирования / Информатика', N'/Обучающие программы/Компьютер и интернет/Основы программирования / Информатика/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC57 AS DateTime), NULL, 26, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (567, 0, 540, N'Методы "слепого" набора текста', N'/Обучающие программы/Компьютер и интернет/Методы "слепого" набора текста/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC5C AS DateTime), NULL, 27, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (568, 0, 540, N'MathCAD. AutoCAD. ArchiCAD', N'/Обучающие программы/Компьютер и интернет/MathCAD. AutoCAD. ArchiCAD/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC62 AS DateTime), NULL, 28, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (569, 0, 540, N'Обучение по продуктам "1C"', N'/Обучающие программы/Компьютер и интернет/Обучение по продуктам "1C"/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC68 AS DateTime), NULL, 29, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (570, 0, 540, N'Обучение Microsoft Office (Word, Excel, PowerPoint и т.д.)', N'/Обучающие программы/Компьютер и интернет/Обучение Microsoft Office (Word, Excel, PowerPoint и т.д.)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC6E AS DateTime), NULL, 30, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (571, 0, 540, N'Обучение Microsoft Windows (2000, XP, Vista и т.д.)', N'/Обучающие программы/Компьютер и интернет/Обучение Microsoft Windows (2000, XP, Vista и т.д.)/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC73 AS DateTime), NULL, 31, NULL, 5)
INSERT [prod].[ProductCategories] ([Id], [Type], [ParentId], [Name], [NamePath], [Status], [InsertedUserId], [UpdatedUserId], [OnlineCategoryUrl], [InsertedDate], [UpdatedDate], [CatOrder], [NotifyOrderStatusUrl], [OnlineCategoryPartnerId]) VALUES (572, 0, 489, N'Менеджмент. Управление', N'/Обучающие программы/Для бизнеса/Менеджмент. Управление/', 1, @User, NULL, NULL, CAST(0x0000A19D00E8DC79 AS DateTime), NULL, 32, NULL, 5)
SET IDENTITY_INSERT [prod].[ProductCategories] OFF
SET NOCOUNT OFF

-- Делаем привязку 1-к-1
print 'Делаем привязку 1-к-1 все уже созданных категории'
INSERT INTO [prod].[PartnerProductCategoryLinks]
([ProductCategoryId],[PartnerId],[NamePath],[IncludeSubcategories],[InsertedDate],[InsertedUserId])
SELECT [ID], @PartnerId, [NamePath], 1, GETDATE(), @User
  FROM [prod].[ProductCategories]
  
DECLARE @notMappedChildCategory int = 338
  
-- Даем разрешения на все уже созданные категории
print 'Даем разрешения на все уже созданные категории'
INSERT INTO [prod].[ProductCategoriesPermissions]
([PartnerId],[CategoryId],[InsertedUserId],[InsertedDate])
SELECT @PartnerId,[ID],@User,GETDATE() 
  FROM [prod].[ProductCategories]

-- Удаляем связку на все дочерние категории 'Акция!!Горящие цены!' ('/Акции/Акция!!Горящие цены!/')
DELETE FROM [prod].[PartnerProductCategoryLinks]
WHERE [PartnerId] = @PartnerId AND [ProductCategoryId] IN (SELECT [Id] FROM [prod].[ProductCategories] WHERE [ParentId] = @notMappedChildCategory)

-- Запрещаем товары из дочерних категорий ('/Акции/Акция!!Горящие цены!/*') грузить в родительскую ('/Акции/Акция!!Горящие цены!/')
UPDATE [prod].[PartnerProductCategoryLinks]
  SET [IncludeSubcategories] = 0
WHERE [PartnerId] = @PartnerId AND [ProductCategoryId] = @notMappedChildCategory

-- Запрещаем товары текущей родительской ('/Акции/Акция!!Горящие цены!/') грузить в ее родительскую ('/Акции/')
UPDATE [prod].[PartnerProductCategoryLinks]
  SET [IncludeSubcategories] = 0
WHERE [PartnerId] = @PartnerId AND [ProductCategoryId] = (SELECT [ParentId] FROM [prod].[ProductCategories] WHERE [Id] = @notMappedChildCategory)

DECLARE @CategoryId [int]
  
-- "Компьютерные игры" валим все в одну корневую категорию и даем разрешение
print '"Компьютерные игры" валим все в одну группу и даем разрешение'
INSERT INTO [prod].[ProductCategories]
([Type],[ParentId],[Name],[NamePath],[Status],[InsertedUserId],[UpdatedUserId],[OnlineCategoryUrl],[InsertedDate],[UpdatedDate],[CatOrder])
VALUES
(0,NULL,'Компьютерные игры','/Компьютерные игры/',1,@User,NULL,NULL,GETDATE(),NULL,5)

SELECT @CategoryId = @@IDENTITY

INSERT INTO [prod].[PartnerProductCategoryLinks]
([ProductCategoryId],[PartnerId],[NamePath],[IncludeSubcategories],[InsertedDate],[InsertedUserId])
VALUES
(@CategoryId,@PartnerId,'/Компьютерные игры/',1, GETDATE(), @User)

INSERT INTO [prod].[ProductCategoriesPermissions]
([PartnerId],[CategoryId],[InsertedUserId],[InsertedDate])
VALUES
(@PartnerId,@CategoryId,@User,GETDATE())

-- "Софт для дома и бизнеса" валим все в одну группу, но не даем разрешение
print '"Софт для дома и бизнеса" валим все в одну группу, но не даем разрешение'
INSERT INTO [prod].[ProductCategories]
([Type],[ParentId],[Name],[NamePath],[Status],[InsertedUserId],[UpdatedUserId],[OnlineCategoryUrl],[InsertedDate],[UpdatedDate],[CatOrder])
VALUES
(0,NULL,'Софт для дома и бизнеса','/Софт для дома и бизнеса/',1,@User,NULL,NULL,GETDATE(),NULL,5)

SELECT @CategoryId = @@IDENTITY

INSERT INTO [prod].[PartnerProductCategoryLinks]
([ProductCategoryId],[PartnerId],[NamePath],[IncludeSubcategories],[InsertedDate],[InsertedUserId])
VALUES
(@CategoryId,@PartnerId,'/Софт для дома и бизнеса/',1, GETDATE(), @User)

-- NOTE: Заметь, нет вставки разрешения разрешения!
set @PartnerId  = null
print 'Для второго партнера'
SELECT @PartnerId = [Id] FROM [prod].[Partners] WHERE [Id] = 2

print 'Делаем второго партнера, если надо'
IF (@PartnerId IS NULL)
BEGIN
  SET IDENTITY_INSERT [prod].[Partners] ON
  INSERT INTO [prod].[Partners]
           ([Id],[Description],
            [InsertedUserId],[UpdatedUserId],
            [Name],[Type],[Status],[ThrustLevel],
            [InsertedDate],[UpdatedDate],
            [CarrierId],FixPriceSupported,[ImportDeliveryRatesEtlPackageId])
     VALUES
           (2,'Тестовый партнер 2',
            @User, NULL,
            'Тестовый партнер 2', 2 /* Offline */,1,0,
            GETDATE(),NULL,
            1,0,NULL)
  SET IDENTITY_INSERT [prod].[Partners] OFF
  
  SET @PartnerId = 2
END

print 'Маппим в корневые категории'
INSERT INTO [prod].[PartnerProductCategoryLinks]
([ProductCategoryId],[PartnerId],[NamePath],[IncludeSubcategories],[InsertedDate],[InsertedUserId])
SELECT [ID], @PartnerId, [NamePath], 1, GETDATE(), @User
  FROM [prod].[ProductCategories]
WHERE [ParentId] IS NULL
  
print 'Даем права на них'
INSERT INTO [prod].[ProductCategoriesPermissions]
([PartnerId],[CategoryId],[InsertedUserId],[InsertedDate])
SELECT @PartnerId,[ID],@User,GETDATE() 
  FROM [prod].[ProductCategories]
WHERE [ParentId] IS NULL

set @PartnerId  = null
print 'Для третьего партнера'
SELECT @PartnerId = [Id] FROM [prod].[Partners] WHERE [Id] = 3

print 'Делаем третьего партнера, если надо'
IF (@PartnerId IS NULL)
BEGIN
  SET IDENTITY_INSERT [prod].[Partners] ON
  INSERT INTO [prod].[Partners]
           ([Id],[Description],[InsertedUserId],[UpdatedUserId],[Name],[Type],[Status],[ThrustLevel],[InsertedDate],[UpdatedDate],FixPriceSupported)
     VALUES
           (3,'Активированный партнер',@User, NULL,'Активированный партнер',0,1,0,GETDATE(),NULL,null)
  SET IDENTITY_INSERT [prod].[Partners] OFF
  
  SET @PartnerId = 3
END

print 'Маппим в корневые категории'
INSERT INTO [prod].[PartnerProductCategoryLinks]
([ProductCategoryId],[PartnerId],[NamePath],[IncludeSubcategories],[InsertedDate],[InsertedUserId])
SELECT [ID], @PartnerId, [NamePath], 1, GETDATE(), @User
  FROM [prod].[ProductCategories]
WHERE [ParentId] IS NULL
  
print 'Даем права на них'
INSERT INTO [prod].[ProductCategoriesPermissions]
([PartnerId],[CategoryId],[InsertedUserId],[InsertedDate])
SELECT @PartnerId,[ID],@User,GETDATE() 
  FROM [prod].[ProductCategories]
WHERE [ParentId] IS NULL

set @PartnerId  = null
print 'Для четвертого партнера'
SELECT @PartnerId = [Id] FROM [prod].[Partners] WHERE [Id] = 4

print 'Делаем четвертого партнера, если надо'
IF (@PartnerId IS NULL)
BEGIN
  SET IDENTITY_INSERT [prod].[Partners] ON
  INSERT INTO [prod].[Partners]
           ([Id],[Description],[InsertedUserId],[UpdatedUserId],[Name],[Type],[Status],[ThrustLevel],[InsertedDate],[UpdatedDate],FixPriceSupported)
     VALUES
           (4,'Деактивированный партнер 4',@User, NULL,'Деактивированный партнер',0,0,0,GETDATE(),NULL,null)
  SET IDENTITY_INSERT [prod].[Partners] OFF
  
  SET @PartnerId = 4
END

print 'Маппим в корневые категории' + Cast( @PartnerId as nvarchar(20) )
INSERT INTO [prod].[PartnerProductCategoryLinks]
([ProductCategoryId],[PartnerId],[NamePath],[IncludeSubcategories],[InsertedDate],[InsertedUserId])
SELECT [ID], @PartnerId, [NamePath], 1, GETDATE(), @User
  FROM [prod].[ProductCategories]
WHERE [ParentId] IS NULL
  
print 'Даем права на них'
INSERT INTO [prod].[ProductCategoriesPermissions]
([PartnerId],[CategoryId],[InsertedUserId],[InsertedDate])
SELECT @PartnerId,[ID],@User,GETDATE() 
  FROM [prod].[ProductCategories]
WHERE [ParentId] IS NULL