//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankSms
    {
        public long Id { get; set; }
        public int TypeCode { get; set; }
        public string Phone { get; set; }
        public string DisplayPhone { get; set; }
        public string Password { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<System.Guid> EtlSessionId { get; set; }
    }
}
