//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientForBankRegistration
    {
        public int Id { get; set; }
        public string MobilePhone { get; set; }
        public string ClientId { get; set; }
        public string Email { get; set; }
        public Nullable<int> Segment { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ErrorStatus { get; set; }
    }
}
