// <auto-generated />
namespace Rapidsoft.VTB24.Reports.Statistics.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ProductViews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductViews));
        
        string IMigrationMetadata.Id
        {
            get { return "201409191006560_ProductViews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
