
IF NOT EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME='YandexGeocodingCache' AND TABLE_SCHEMA = 'Geopoints') 
BEGIN
CREATE TABLE [Geopoints].[YandexGeocodingCache](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Address] [nvarchar](256) NOT NULL,
	[RawResponse] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_YandexGeocodingCache] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END;

IF NOT EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME='GoogleGeocodingCache' AND TABLE_SCHEMA = 'Geopoints') 
BEGIN
CREATE TABLE [Geopoints].[GoogleGeocodingCache](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Address] [nvarchar](256) NOT NULL,
	[RawResponse] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_GoogleGeocodingCache] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END;