//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RapidSoft.Loaylty.PartnersConnector.Common.DTO
{
    using System.ComponentModel.DataAnnotations;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/XMLSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd", IsNullable = false)]
    public partial class FixPriceResult
    {
        private string errorMessasgeField;

        private System.Nullable<decimal> actualPriceField;

        private System.Nullable<System.DateTime> utcDateTimeField;

        private int? confirmedField;

        private string reasonField;

        private string reasonCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ErrorMessasge
        {
            get
            {
                return this.errorMessasgeField;
            }
            set
            {
                this.errorMessasgeField = value;
            }
        }

        /// <remarks/>
        public System.Nullable<decimal> ActualPrice
        {
            get
            {
                return this.actualPriceField;
            }
            set
            {
                this.actualPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> UtcDateTime
        {
            get
            {
                return this.utcDateTimeField;
            }
            set
            {
                this.utcDateTimeField = value;
            }
        }

        [Required]
        public int? Confirmed
        {
            get
            {
                return this.confirmedField;
            }
            set
            {
                this.confirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }
    }
}