INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'010', N'АНТАРКТИДА', NULL, N'AQ', N'ATA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'100', N'БОЛГАРИЯ', N'Республика Болгария', N'BG', N'BGR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'104', N'МЬЯНМА', N'Республика Союза Мьянма', N'MM', N'MMR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'108', N'БУРУНДИ', N'Республика Бурунди', N'BI', N'BDI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'112', N'БЕЛАРУСЬ', N'Республика Беларусь', N'BY', N'BLR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'116', N'КАМБОДЖА', N'Королевство Камбоджа', N'KH', N'KHM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'012', N'АЛЖИР', N'Алжирская Народная Демократическая Республика', N'DZ', N'DZA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'120', N'КАМЕРУН', N'Республика Камерун', N'CM', N'CMR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'124', N'КАНАДА', NULL, N'CA', N'CAN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'132', N'КАБО-ВЕРДЕ', N'Республика Кабо-Верде', N'CV', N'CPV')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'136', N'ОСТРОВА КАЙМАН', NULL, N'KY', N'CYM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'140', N'ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА', NULL, N'CF', N'CAF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'144', N'ШРИ-ЛАНКА', N'Демократическая Социалистическая Республика Шри-Ланка', N'LK', N'LKA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'148', N'ЧАД', N'Республика Чад', N'TD', N'TCD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'152', N'ЧИЛИ', N'Республика Чили', N'CL', N'CHL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'156', N'КИТАЙ', N'Китайская Народная Республика', N'CN', N'CHN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'158', N'ТАЙВАНЬ (КИТАЙ)', NULL, N'TW', N'TWN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'016', N'АМЕРИКАНСКОЕ САМОА', NULL, N'AS', N'ASM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'162', N'ОСТРОВ РОЖДЕСТВА', NULL, N'CX', N'CXR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'166', N'КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА', NULL, N'CC', N'CCK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'170', N'КОЛУМБИЯ', N'Республика Колумбия', N'CO', N'COL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'174', N'КОМОРЫ', N'Союз Коморы', N'KM', N'COM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'175', N'МАЙОТТА', NULL, N'YT', N'MYT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'178', N'КОНГО', N'Республика Конго', N'CG', N'COG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'180', N'КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', N'Демократическая Республика Конго', N'CD', N'COD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'184', N'ОСТРОВА КУКА', NULL, N'CK', N'COK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'188', N'КОСТА-РИКА', N'Республика Коста-Рика', N'CR', N'CRI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'191', N'ХОРВАТИЯ', N'Республика Хорватия', N'HR', N'HRV')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'192', N'КУБА', N'Республика Куба', N'CU', N'CUB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'196', N'КИПР', N'Республика Кипр', N'CY', N'CYP')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'020', N'АНДОРРА', N'Княжество Андорра', N'AD', N'AND')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'203', N'ЧЕШСКАЯ РЕСПУБЛИКА', NULL, N'CZ', N'CZE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'204', N'БЕНИН', N'Республика Бенин', N'BJ', N'BEN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'208', N'ДАНИЯ', N'Королевство Дания', N'DK', N'DNK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'212', N'ДОМИНИКА', N'Содружество Доминики', N'DM', N'DMA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'214', N'ДОМИНИКАНСКАЯ РЕСПУБЛИКА', NULL, N'DO', N'DOM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'218', N'ЭКВАДОР', N'Республика Эквадор', N'EC', N'ECU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'222', N'ЭЛЬ-САЛЬВАДОР', N'Республика Эль-Сальвадор', N'SV', N'SLV')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'226', N'ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ', N'Республика Экваториальная Гвинея', N'GQ', N'GNQ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'231', N'ЭФИОПИЯ', N'Федеративная Демократическая Республика Эфиопия', N'ET', N'ETH')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'232', N'ЭРИТРЕЯ', NULL, N'ER', N'ERI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'233', N'ЭСТОНИЯ', N'Эстонская Республика', N'EE', N'EST')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'234', N'ФАРЕРСКИЕ ОСТРОВА', NULL, N'FO', N'FRO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'238', N'ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)', NULL, N'FK', N'FLK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'239', N'ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА', NULL, N'GS', N'SGS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'024', N'АНГОЛА', N'Республика Ангола', N'AO', N'AGO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'242', N'ФИДЖИ', N'Республика Фиджи', N'FJ', N'FJI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'246', N'ФИНЛЯНДИЯ', N'Финляндская Республика', N'FI', N'FIN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'248', N'ЭЛАНДСКИЕ ОСТРОВА', NULL, N'АХ', N'ALA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'250', N'ФРАНЦИЯ', N'Французская Республика', N'FR', N'FRA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'254', N'ФРАНЦУЗСКАЯ ГВИАНА', NULL, N'GF', N'GUF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'258', N'ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ', NULL, N'PF', N'PYF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'260', N'ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ', NULL, N'TF', N'ATF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'262', N'ДЖИБУТИ', N'Республика Джибути', N'DJ', N'DJI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'266', N'ГАБОН', N'Габонская Республика', N'GA', N'GAB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'268', N'ГРУЗИЯ', NULL, N'GE', N'GEO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'270', N'ГАМБИЯ', N'Республика Гамбия', N'GM', N'GMB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'275', N'ПАЛЕСТИНСКАЯ ТЕРРИТОРИЯ, ОККУПИРОВАННАЯ', N'Оккупированная Палестинская территория', N'PS', N'PSE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'276', N'ГЕРМАНИЯ', N'Федеративная Республика Германия', N'DE', N'DEU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'028', N'АНТИГУА И БАРБУДА', NULL, N'AG', N'ATG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'288', N'ГАНА', N'Республика Гана', N'GH', N'GHA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'292', N'ГИБРАЛТАР', NULL, N'GI', N'GIB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'296', N'КИРИБАТИ', N'Республика Кирибати', N'KI', N'KIR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'300', N'ГРЕЦИЯ', N'Греческая Республика', N'GR', N'GRC')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'304', N'ГРЕНЛАНДИЯ', NULL, N'GL', N'GRL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'308', N'ГРЕНАДА', NULL, N'GD', N'GRD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'031', N'АЗЕРБАЙДЖАН', N'Республика Азербайджан', N'AZ', N'AZE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'312', N'ГВАДЕЛУПА', NULL, N'GP', N'GLP')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'316', N'ГУАМ', NULL, N'GU', N'GUM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'032', N'АРГЕНТИНА', N'Аргентинская Республика', N'AR', N'ARG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'320', N'ГВАТЕМАЛА', N'Республика Гватемала', N'GT', N'GTM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'324', N'ГВИНЕЯ', N'Гвинейская Республика', N'GN', N'GIN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'328', N'ГАЙАНА', N'Республика Гайана', N'GY', N'GUY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'332', N'ГАИТИ', N'Республика Гаити', N'HT', N'HTI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'334', N'ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД', NULL, N'HM', N'HMD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'336', N'ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО - ГОРОД ВАТИКАН)', NULL, N'VA', N'VAT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'340', N'ГОНДУРАС', N'Республика Гондурас', N'HN', N'HND')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'344', N'ГОНКОНГ', N'Специальный административный регион Китая Гонконг', N'HK', N'HKG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'348', N'ВЕНГРИЯ', N'Венгрия', N'HU', N'HUN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'352', N'ИСЛАНДИЯ', N'Республика Исландия', N'IS', N'ISL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'356', N'ИНДИЯ', N'Республика Индия', N'IN', N'IND')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'036', N'АВСТРАЛИЯ', NULL, N'AU', N'AUS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'360', N'ИНДОНЕЗИЯ', N'Республика Индонезия', N'ID', N'IDN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'364', N'ИРАН, ИСЛАМСКАЯ РЕСПУБЛИКА', N'Исламская Республика Иран', N'IR', N'IRN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'368', N'ИРАК', N'Республика Ирак', N'IQ', N'IRQ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'372', N'ИРЛАНДИЯ', NULL, N'IE', N'IRL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'376', N'ИЗРАИЛЬ', N'Государство Израиль', N'IL', N'ISR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'380', N'ИТАЛИЯ', N'Итальянская Республика', N'IT', N'ITA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'384', N'КОТ Д''ИВУАР', N'Республика Кот д''Ивуар', N'CI', N'CIV')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'388', N'ЯМАЙКА', NULL, N'JM', N'JAM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'392', N'ЯПОНИЯ', NULL, N'JP', N'JPN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'398', N'КАЗАХСТАН', N'Республика Казахстан', N'KZ', N'KAZ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'004', N'АФГАНИСТАН', N'Переходное Исламское Государство Афганистан', N'AF', N'AFG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'040', N'АВСТРИЯ', N'Австрийская Республика', N'AT', N'AUT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'400', N'ИОРДАНИЯ', N'Иорданское Хашимитское Королевство', N'JO', N'JOR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'404', N'КЕНИЯ', N'Республика Кения', N'KE', N'KEN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'408', N'КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', N'Корейская Народно-Демократическая Республика', N'KP', N'PRK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'410', N'КОРЕЯ, РЕСПУБЛИКА', N'Республика Корея', N'KR', N'KOR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'414', N'КУВЕЙТ', N'Государство Кувейт', N'KW', N'KWT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'417', N'КИРГИЗИЯ', N'Киргизская Республика', N'KG', N'KGZ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'418', N'ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', NULL, N'LA', N'LAO')
GO
print 'Processed 100 total records'
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'422', N'ЛИВАН', N'Ливанская Республика', N'LB', N'LBN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'426', N'ЛЕСОТО', N'Королевство Лесото', N'LS', N'LSO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'428', N'ЛАТВИЯ', N'Латвийская Республика', N'LV', N'LVA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'430', N'ЛИБЕРИЯ', N'Республика Либерия', N'LR', N'LBR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'434', N'ЛИВИЯ', N'Ливия', N'LY', N'LBY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'438', N'ЛИХТЕНШТЕЙН', N'Княжество Лихтенштейн', N'LI', N'LIE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'044', N'БАГАМЫ', N'Содружество Багамы', N'BS', N'BHS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'440', N'ЛИТВА', N'Литовская Республика', N'LT', N'LTU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'442', N'ЛЮКСЕМБУРГ', N'Великое Герцогство Люксембург', N'LU', N'LUX')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'446', N'МАКАО', N'Специальный административный регион Китая Макао', N'MO', N'MAC')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'450', N'МАДАГАСКАР', N'Республика Мадагаскар', N'MG', N'MDG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'454', N'МАЛАВИ', N'Республика Малави', N'MW', N'MWI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'458', N'МАЛАЙЗИЯ', NULL, N'MY', N'MYS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'462', N'МАЛЬДИВЫ', N'Мальдивская Республика', N'MV', N'MDV')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'466', N'МАЛИ', N'Республика Мали', N'ML', N'MLI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'470', N'МАЛЬТА', N'Республика Мальта', N'MT', N'MLT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'474', N'МАРТИНИКА', NULL, N'MQ', N'MTQ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'478', N'МАВРИТАНИЯ', N'Исламская Республика Мавритания', N'MR', N'MRT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'048', N'БАХРЕЙН', N'Королевство Бахрейн', N'BH', N'BHR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'480', N'МАВРИКИЙ', N'Республика Маврикий', N'MU', N'MUS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'484', N'МЕКСИКА', N'Мексиканские Соединенные Штаты', N'MX', N'MEX')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'492', N'МОНАКО', N'Княжество Монако', N'MC', N'MCO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'496', N'МОНГОЛИЯ', NULL, N'MN', N'MNG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'498', N'МОЛДОВА, РЕСПУБЛИКА', N'Республика Молдова', N'MD', N'MDA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'499', N'ЧЕРНОГОРИЯ', NULL, N'ME', N'MNE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'050', N'БАНГЛАДЕШ', N'Народная Республика Бангладеш', N'BD', N'BGD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'500', N'МОНТСЕРРАТ', NULL, N'MS', N'MSR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'504', N'МАРОККО', N'Королевство Марокко', N'MA', N'MAR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'508', N'МОЗАМБИК', N'Республика Мозамбик', N'MZ', N'MOZ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'051', N'АРМЕНИЯ', N'Республика Армения', N'AM', N'ARM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'512', N'ОМАН', N'Султанат Оман', N'OM', N'OMN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'516', N'НАМИБИЯ', N'Республика Намибия', N'NA', N'NAM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'052', N'БАРБАДОС', NULL, N'BB', N'BRB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'520', N'НАУРУ', N'Республика Науру', N'NR', N'NRU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'524', N'НЕПАЛ', N'Федеративная Демократическая Республика Непал', N'NP', N'NPL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'528', N'НИДЕРЛАНДЫ', N'Королевство Нидерландов', N'NL', N'NLD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'531', N'КЮРАСАО', NULL, N'CW', N'CUW')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'533', N'АРУБА', NULL, N'AW', N'ABW')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'534', N'СЕН-МАРТЕН (нидерландская часть)', NULL, N'SX', N'SXM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'535', N'БОНЭЙР, СИНТ-ЭСТАТИУС И САБА', NULL, N'BQ', N'BES')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'540', N'НОВАЯ КАЛЕДОНИЯ', NULL, N'NC', N'NCL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'548', N'ВАНУАТУ', N'Республика Вануату', N'VU', N'VUT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'554', N'НОВАЯ ЗЕЛАНДИЯ', NULL, N'NZ', N'NZL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'558', N'НИКАРАГУА', N'Республика Никарагуа', N'NI', N'NIC')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'056', N'БЕЛЬГИЯ', N'Королевство Бельгии', N'BE', N'BEL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'562', N'НИГЕР', N'Республика Нигер', N'NE', N'NER')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'566', N'НИГЕРИЯ', N'Федеративная Республика Нигерия', N'NG', N'NGA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'570', N'НИУЭ', N'Ниуэ', N'NU', N'NIU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'574', N'ОСТРОВ НОРФОЛК', NULL, N'NF', N'NFK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'578', N'НОРВЕГИЯ', N'Королевство Норвегия', N'NO', N'NOR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'580', N'СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА', N'Содружество Северных Марианских островов', N'MP', N'MNP')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'581', N'МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ', NULL, N'UM', N'UMI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'583', N'МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ', N'Федеративные штаты Микронезии', N'FM', N'FSM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'584', N'МАРШАЛЛОВЫ ОСТРОВА', N'Республика Маршалловы Острова', N'MH', N'MHL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'585', N'ПАЛАУ', N'Республика Палау', N'PW', N'PLW')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'586', N'ПАКИСТАН', N'Исламская Республика Пакистан', N'PK', N'PAK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'591', N'ПАНАМА', N'Республика Панама', N'PA', N'PAN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'598', N'ПАПУА-НОВАЯ ГВИНЕЯ', NULL, N'PG', N'PNG')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'060', N'БЕРМУДЫ', NULL, N'BM', N'BMU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'600', N'ПАРАГВАЙ', N'Республика Парагвай', N'PY', N'PRY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'604', N'ПЕРУ', N'Республика Перу', N'PE', N'PER')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'608', N'ФИЛИППИНЫ', N'Республика Филиппины', N'PH', N'PHL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'612', N'ПИТКЕРН', NULL, N'PN', N'PCN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'616', N'ПОЛЬША', N'Республика Польша', N'PL', N'POL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'620', N'ПОРТУГАЛИЯ', N'Португальская Республика', N'PT', N'PRT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'624', N'ГВИНЕЯ-БИСАУ', N'Республика Гвинея-Бисау', N'GW', N'GNB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'626', N'ТИМОР-ЛЕСТЕ', N'Демократическая Республика Тимор-Лесте', N'TL', N'TLS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'630', N'ПУЭРТО-РИКО', NULL, N'PR', N'PRI')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'634', N'КАТАР', N'Государство Катар', N'QA', N'QAT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'638', N'РЕЮНЬОН', NULL, N'RE', N'REU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'064', N'БУТАН', N'Королевство Бутан', N'BT', N'BTN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'642', N'РУМЫНИЯ', NULL, N'RO', N'ROU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'643', N'Россия', N'Российская Федерация', N'RU', N'RUS')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'646', N'РУАНДА', N'Руандийская Республика', N'RW', N'RWA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'652', N'СЕН-БАРТЕЛЕМИ', NULL, N'BL', N'BLM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'654', N'СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ', NULL, N'SH', N'SHN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'659', N'СЕНТ-КИТС И НЕВИС', NULL, N'KN', N'KNA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'660', N'АНГИЛЬЯ', NULL, N'AI', N'AIA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'662', N'СЕНТ-ЛЮСИЯ', NULL, N'LC', N'LCA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'663', N'СЕН-МАРТЕН', NULL, N'MF', N'MAF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'666', N'СЕН-ПЬЕР И МИКЕЛОН', NULL, N'PM', N'SPM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'670', N'СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ', NULL, N'VC', N'VCT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'674', N'САН-МАРИНО', N'Республика Сан-Марино', N'SM', N'SMR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'678', N'САН-ТОМЕ И ПРИНСИПИ', N'Демократическая Республика Сан-Томе и Принсипи', N'ST', N'STP')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'068', N'БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО', N'Многонациональное Государство Боливия', N'BO', N'BOL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'682', N'САУДОВСКАЯ АРАВИЯ', N'Королевство Саудовская Аравия', N'SA', N'SAU')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'686', N'СЕНЕГАЛ', N'Республика Сенегал', N'SN', N'SEN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'688', N'СЕРБИЯ', N'Республика Сербия', N'RS', N'SRB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'690', N'СЕЙШЕЛЫ', N'Республика Сейшелы', N'SC', N'SYC')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'694', N'СЬЕРРА-ЛЕОНЕ', N'Республика Сьерра-Леоне', N'SL', N'SLE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'070', N'БОСНИЯ И ГЕРЦЕГОВИНА', NULL, N'BA', N'BIH')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'702', N'СИНГАПУР', N'Республика Сингапур', N'SG', N'SGP')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'703', N'СЛОВАКИЯ', N'Словацкая Республика', N'SK', N'SVK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'704', N'ВЬЕТНАМ', N'Социалистическая Республика Вьетнам', N'VN', N'VNM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'705', N'СЛОВЕНИЯ', N'Республика Словения', N'SI', N'SVN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'706', N'СОМАЛИ', N'Сомалийская Республика', N'SO', N'SOM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'710', N'ЮЖНАЯ АФРИКА', N'Южно-Африканская Республика', N'ZA', N'ZAF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'716', N'ЗИМБАБВЕ', N'Республика Зимбабве', N'ZW', N'ZWE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'072', N'БОТСВАНА', N'Республика Ботсвана', N'BW', N'BWA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'724', N'ИСПАНИЯ', N'Королевство Испания', N'ES', N'ESP')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'728', N'ЮЖНЫЙ СУДАН', N'Республика Южный Судан', N'SS', N'SSD')
GO
print 'Processed 200 total records'
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'729', N'СУДАН', N'Республика Судан', N'SD', N'SDN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'732', N'ЗАПАДНАЯ САХАРА Росстандарта от 14.12.2011 N 1514-ст', NULL, N'EH', N'ESH')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'074', N'ОСТРОВ БУВЕ', NULL, N'BV', N'BVT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'740', N'СУРИНАМ', N'Республика Суринам', N'SR', N'SUR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'744', N'ШПИЦБЕРГЕН И ЯН МАЙЕН', NULL, N'SJ', N'SJM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'748', N'СВАЗИЛЕНД', N'Королевство Свазиленд', N'SZ', N'SWZ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'752', N'ШВЕЦИЯ', N'Королевство Швеция', N'SE', N'SWE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'756', N'ШВЕЙЦАРИЯ', N'Швейцарская Конфедерация', N'CH', N'CHE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'076', N'БРАЗИЛИЯ', N'Федеративная Республика Бразилия', N'BR', N'BRA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'760', N'СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА', NULL, N'SY', N'SYR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'762', N'ТАДЖИКИСТАН', N'Республика Таджикистан', N'TJ', N'TJK')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'764', N'ТАИЛАНД', N'Королевство Таиланд', N'TH', N'THA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'768', N'ТОГО', N'Тоголезская Республика', N'TG', N'TGO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'772', N'ТОКЕЛАУ', NULL, N'TK', N'TKL')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'776', N'ТОНГА', N'Королевство Тонга', N'TO', N'TON')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'780', N'ТРИНИДАД И ТОБАГО', N'Республика Тринидад и Тобаго', N'TT', N'TTO')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'784', N'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ', NULL, N'AE', N'ARE')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'788', N'ТУНИС', N'Тунисская Республика', N'TN', N'TUN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'792', N'ТУРЦИЯ', N'Турецкая Республика', N'TR', N'TUR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'795', N'ТУРКМЕНИЯ', N'Туркменистан', N'TM', N'TKM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'796', N'ОСТРОВА ТЕРКС И КАЙКОС', NULL, N'TC', N'TCA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'798', N'ТУВАЛУ', NULL, N'TV', N'TUV')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'008', N'АЛБАНИЯ', N'Республика Албания', N'AL', N'ALB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'800', N'УГАНДА', N'Республика Уганда', N'UG', N'UGA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'804', N'УКРАИНА', NULL, N'UA', N'UKR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'807', N'РЕСПУБЛИКА МАКЕДОНИЯ', NULL, N'MK', N'MKD')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'818', N'ЕГИПЕТ', N'Арабская Республика Египет', N'EG', N'EGY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'826', N'СОЕДИНЕННОЕ КОРОЛЕВСТВО', N'Соединенное Королевство Великобритании и Северной Ирландии', N'GB', N'GBR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'831', N'ГЕРНСИ', NULL, N'GG', N'GGY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'832', N'ДЖЕРСИ', NULL, N'JE', N'JEY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'833', N'ОСТРОВ МЭН', NULL, N'IM', N'IMN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'834', N'ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА', N'Объединенная Республика Танзания', N'TZ', N'TZA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'084', N'БЕЛИЗ', NULL, N'BZ', N'BLZ')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'840', N'СОЕДИНЕННЫЕ ШТАТЫ', N'Соединенные Штаты Америки', N'US', N'USA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'850', N'ВИРГИНСКИЕ ОСТРОВА, США', N'Виргинские острова Соединенных Штатов', N'VI', N'VIR')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'854', N'БУРКИНА-ФАСО', NULL, N'BF', N'BFA')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'858', N'УРУГВАЙ', N'Восточная Республика Уругвай', N'UY', N'URY')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'086', N'БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ', NULL, N'IO', N'IOT')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'860', N'УЗБЕКИСТАН', N'Республика Узбекистан', N'UZ', N'UZB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'862', N'ВЕНЕСУЭЛА БОЛИВАРИАНСКАЯ РЕСПУБЛИКА', N'Боливарианская Республика Венесуэла', N'VE', N'VEN')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'876', N'УОЛЛИС И ФУТУНА', NULL, N'WF', N'WLF')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'882', N'САМОА', N'Независимое Государство Самоа', N'WS', N'WSM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'887', N'ЙЕМЕН', N'Йеменская Республика', N'YE', N'YEM')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'894', N'ЗАМБИЯ', N'Республика Замбия', N'ZM', N'ZMB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'895', N'АБХАЗИЯ', N'Республика Абхазия', N'AB', N'ABH')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'896', N'ЮЖНАЯ ОСЕТИЯ', N'Республика Южная Осетия', N'OS', N'OST')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'090', N'СОЛОМОНОВЫ ОСТРОВА', NULL, N'SB', N'SLB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'092', N'ВИРГИНСКИЕ ОСТРОВА, БРИТАНСКИЕ', N'Британские Виргинские острова', N'VG', N'VGB')
INSERT [Geopoints].[OKSMCountries] ([NumberCode], [Name], [Description], [Alpha2Code], [Alpha3Code]) VALUES (N'096', N'БРУНЕЙ-ДАРУССАЛАМ', NULL, N'BN', N'BRN')