// <auto-generated />
namespace Vtb24.Site.Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Security_Change_Login : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Security_Change_Login));
        
        string IMigrationMetadata.Id
        {
            get { return "201311111646455_Security_Change_Login"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
