// <auto-generated />
namespace Vtb24.Site.Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Security_Otp_Statistics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Security_Otp_Statistics));
        
        string IMigrationMetadata.Id
        {
            get { return "201306021239321_Security_Otp_Statistics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
