// <auto-generated />
namespace Vtb24.Site.Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Otp_AntiSpoof_Key_Refactoring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Otp_AntiSpoof_Key_Refactoring));
        
        string IMigrationMetadata.Id
        {
            get { return "201306251725262_Otp_AntiSpoof_Key_Refactoring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
