//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vtb24.Site.Services.ProductCatalogBasketService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBase", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Outp" +
        "utResults")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vtb24.Site.Services.ProductCatalogBasketService.BasketResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult))]
    internal partial class ResultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ResultDescription {
            get {
                return this.ResultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDescriptionField, value) != true)) {
                    this.ResultDescriptionField = value;
                    this.RaisePropertyChanged("ResultDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBasketItemResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Outp" +
        "utResults")]
    [System.SerializableAttribute()]
    internal partial class GetBasketItemResult : Vtb24.Site.Services.ProductCatalogBasketService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.BasketItem ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.BasketItem Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBasketItemsResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Outp" +
        "utResults")]
    [System.SerializableAttribute()]
    internal partial class GetBasketItemsResult : Vtb24.Site.Services.ProductCatalogBasketService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.BasketItem[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.BasketItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasketResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Outp" +
        "utResults")]
    [System.SerializableAttribute()]
    internal partial class BasketResult : Vtb24.Site.Services.ProductCatalogBasketService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.BasketItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.BasketItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasketManageResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Outp" +
        "utResults")]
    [System.SerializableAttribute()]
    internal partial class BasketManageResult : Vtb24.Site.Services.ProductCatalogBasketService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasketItem", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Enti" +
        "ties")]
    [System.SerializableAttribute()]
    internal partial class BasketItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.ProductAvailabilityStatuses AvailabilityStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BasketItemGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FixedPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductsQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceRurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.ProductAvailabilityStatuses AvailabilityStatus {
            get {
                return this.AvailabilityStatusField;
            }
            set {
                if ((this.AvailabilityStatusField.Equals(value) != true)) {
                    this.AvailabilityStatusField = value;
                    this.RaisePropertyChanged("AvailabilityStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> BasketItemGroupId {
            get {
                return this.BasketItemGroupIdField;
            }
            set {
                if ((this.BasketItemGroupIdField.Equals(value) != true)) {
                    this.BasketItemGroupIdField = value;
                    this.RaisePropertyChanged("BasketItemGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FixedPrice {
            get {
                return this.FixedPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.FixedPriceField, value) != true)) {
                    this.FixedPriceField = value;
                    this.RaisePropertyChanged("FixedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((this.ItemPriceField.Equals(value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ProductsQuantity {
            get {
                return this.ProductsQuantityField;
            }
            set {
                if ((this.ProductsQuantityField.Equals(value) != true)) {
                    this.ProductsQuantityField = value;
                    this.RaisePropertyChanged("ProductsQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal TotalPriceRur {
            get {
                return this.TotalPriceRurField;
            }
            set {
                if ((this.TotalPriceRurField.Equals(value) != true)) {
                    this.TotalPriceRurField = value;
                    this.RaisePropertyChanged("TotalPriceRur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Enti" +
        "ties")]
    [System.SerializableAttribute()]
    internal partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BasePriceRURField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BasePriceRurDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNamePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryOfOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DownloadableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HallPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelStarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncludedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeliveredByEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKidsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPremiereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecommendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastChangedUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ManufacturerWarrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.ProductModerationStatuses ModerationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageExtentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.ProductParam[] ParamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerformanceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerformedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PickupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PicturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceRURField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordingLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vtb24.Site.Services.ProductCatalogBasketService.ProductStatuses StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusChangedCauseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusChangedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusChangedUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableOfContentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TargetAudiencesIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypePrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorldRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Adult {
            get {
                return this.AdultField;
            }
            set {
                if ((object.ReferenceEquals(this.AdultField, value) != true)) {
                    this.AdultField = value;
                    this.RaisePropertyChanged("Adult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string[] Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<decimal> BasePriceRUR {
            get {
                return this.BasePriceRURField;
            }
            set {
                if ((this.BasePriceRURField.Equals(value) != true)) {
                    this.BasePriceRURField = value;
                    this.RaisePropertyChanged("BasePriceRUR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> BasePriceRurDate {
            get {
                return this.BasePriceRurDateField;
            }
            set {
                if ((this.BasePriceRurDateField.Equals(value) != true)) {
                    this.BasePriceRurDateField = value;
                    this.RaisePropertyChanged("BasePriceRurDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Binding {
            get {
                return this.BindingField;
            }
            set {
                if ((object.ReferenceEquals(this.BindingField, value) != true)) {
                    this.BindingField = value;
                    this.RaisePropertyChanged("Binding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CategoryNamePath {
            get {
                return this.CategoryNamePathField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNamePathField, value) != true)) {
                    this.CategoryNamePathField = value;
                    this.RaisePropertyChanged("CategoryNamePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CountryOfOrigin {
            get {
                return this.CountryOfOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryOfOriginField, value) != true)) {
                    this.CountryOfOriginField = value;
                    this.RaisePropertyChanged("CountryOfOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DataTour {
            get {
                return this.DataTourField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTourField, value) != true)) {
                    this.DataTourField = value;
                    this.RaisePropertyChanged("DataTour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Days {
            get {
                return this.DaysField;
            }
            set {
                if ((this.DaysField.Equals(value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Delivery {
            get {
                return this.DeliveryField;
            }
            set {
                if ((this.DeliveryField.Equals(value) != true)) {
                    this.DeliveryField = value;
                    this.RaisePropertyChanged("Delivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Downloadable {
            get {
                return this.DownloadableField;
            }
            set {
                if ((this.DownloadableField.Equals(value) != true)) {
                    this.DownloadableField = value;
                    this.RaisePropertyChanged("Downloadable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ExternalLocationId {
            get {
                return this.ExternalLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalLocationIdField, value) != true)) {
                    this.ExternalLocationIdField = value;
                    this.RaisePropertyChanged("ExternalLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string HallPlan {
            get {
                return this.HallPlanField;
            }
            set {
                if ((object.ReferenceEquals(this.HallPlanField, value) != true)) {
                    this.HallPlanField = value;
                    this.RaisePropertyChanged("HallPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string HotelStars {
            get {
                return this.HotelStarsField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelStarsField, value) != true)) {
                    this.HotelStarsField = value;
                    this.RaisePropertyChanged("HotelStars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Included {
            get {
                return this.IncludedField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedField, value) != true)) {
                    this.IncludedField = value;
                    this.RaisePropertyChanged("Included");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime InsertedDate {
            get {
                return this.InsertedDateField;
            }
            set {
                if ((this.InsertedDateField.Equals(value) != true)) {
                    this.InsertedDateField = value;
                    this.RaisePropertyChanged("InsertedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsActionPrice {
            get {
                return this.IsActionPriceField;
            }
            set {
                if ((this.IsActionPriceField.Equals(value) != true)) {
                    this.IsActionPriceField = value;
                    this.RaisePropertyChanged("IsActionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsDeliveredByEmail {
            get {
                return this.IsDeliveredByEmailField;
            }
            set {
                if ((this.IsDeliveredByEmailField.Equals(value) != true)) {
                    this.IsDeliveredByEmailField = value;
                    this.RaisePropertyChanged("IsDeliveredByEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsKids {
            get {
                return this.IsKidsField;
            }
            set {
                if ((this.IsKidsField.Equals(value) != true)) {
                    this.IsKidsField = value;
                    this.RaisePropertyChanged("IsKids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsPremiere {
            get {
                return this.IsPremiereField;
            }
            set {
                if ((this.IsPremiereField.Equals(value) != true)) {
                    this.IsPremiereField = value;
                    this.RaisePropertyChanged("IsPremiere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsRecommended {
            get {
                return this.IsRecommendedField;
            }
            set {
                if ((this.IsRecommendedField.Equals(value) != true)) {
                    this.IsRecommendedField = value;
                    this.RaisePropertyChanged("IsRecommended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime LastChangedDate {
            get {
                return this.LastChangedDateField;
            }
            set {
                if ((this.LastChangedDateField.Equals(value) != true)) {
                    this.LastChangedDateField = value;
                    this.RaisePropertyChanged("LastChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LastChangedUser {
            get {
                return this.LastChangedUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LastChangedUserField, value) != true)) {
                    this.LastChangedUserField = value;
                    this.RaisePropertyChanged("LastChangedUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool ManufacturerWarranty {
            get {
                return this.ManufacturerWarrantyField;
            }
            set {
                if ((this.ManufacturerWarrantyField.Equals(value) != true)) {
                    this.ManufacturerWarrantyField = value;
                    this.RaisePropertyChanged("ManufacturerWarranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Meal {
            get {
                return this.MealField;
            }
            set {
                if ((object.ReferenceEquals(this.MealField, value) != true)) {
                    this.MealField = value;
                    this.RaisePropertyChanged("Meal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Media {
            get {
                return this.MediaField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaField, value) != true)) {
                    this.MediaField = value;
                    this.RaisePropertyChanged("Media");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.ProductModerationStatuses ModerationStatus {
            get {
                return this.ModerationStatusField;
            }
            set {
                if ((this.ModerationStatusField.Equals(value) != true)) {
                    this.ModerationStatusField = value;
                    this.RaisePropertyChanged("ModerationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string OriginalName {
            get {
                return this.OriginalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalNameField, value) != true)) {
                    this.OriginalNameField = value;
                    this.RaisePropertyChanged("OriginalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PageExtent {
            get {
                return this.PageExtentField;
            }
            set {
                if ((this.PageExtentField.Equals(value) != true)) {
                    this.PageExtentField = value;
                    this.RaisePropertyChanged("PageExtent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.ProductParam[] Param {
            get {
                return this.ParamField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamField, value) != true)) {
                    this.ParamField = value;
                    this.RaisePropertyChanged("Param");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Part {
            get {
                return this.PartField;
            }
            set {
                if ((this.PartField.Equals(value) != true)) {
                    this.PartField = value;
                    this.RaisePropertyChanged("Part");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PartnerCategoryId {
            get {
                return this.PartnerCategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCategoryIdField, value) != true)) {
                    this.PartnerCategoryIdField = value;
                    this.RaisePropertyChanged("PartnerCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PartnerProductId {
            get {
                return this.PartnerProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerProductIdField, value) != true)) {
                    this.PartnerProductIdField = value;
                    this.RaisePropertyChanged("PartnerProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PerformanceType {
            get {
                return this.PerformanceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceTypeField, value) != true)) {
                    this.PerformanceTypeField = value;
                    this.RaisePropertyChanged("PerformanceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PerformedBy {
            get {
                return this.PerformedByField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformedByField, value) != true)) {
                    this.PerformedByField = value;
                    this.RaisePropertyChanged("PerformedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Pickup {
            get {
                return this.PickupField;
            }
            set {
                if ((this.PickupField.Equals(value) != true)) {
                    this.PickupField = value;
                    this.RaisePropertyChanged("Pickup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string[] Pictures {
            get {
                return this.PicturesField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturesField, value) != true)) {
                    this.PicturesField = value;
                    this.RaisePropertyChanged("Pictures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal PriceBase {
            get {
                return this.PriceBaseField;
            }
            set {
                if ((this.PriceBaseField.Equals(value) != true)) {
                    this.PriceBaseField = value;
                    this.RaisePropertyChanged("PriceBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal PriceRUR {
            get {
                return this.PriceRURField;
            }
            set {
                if ((this.PriceRURField.Equals(value) != true)) {
                    this.PriceRURField = value;
                    this.RaisePropertyChanged("PriceRUR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RecordingLength {
            get {
                return this.RecordingLengthField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordingLengthField, value) != true)) {
                    this.RecordingLengthField = value;
                    this.RaisePropertyChanged("RecordingLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SalesNotes {
            get {
                return this.SalesNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesNotesField, value) != true)) {
                    this.SalesNotesField = value;
                    this.RaisePropertyChanged("SalesNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Starring {
            get {
                return this.StarringField;
            }
            set {
                if ((object.ReferenceEquals(this.StarringField, value) != true)) {
                    this.StarringField = value;
                    this.RaisePropertyChanged("Starring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Vtb24.Site.Services.ProductCatalogBasketService.ProductStatuses Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StatusChangedCause {
            get {
                return this.StatusChangedCauseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusChangedCauseField, value) != true)) {
                    this.StatusChangedCauseField = value;
                    this.RaisePropertyChanged("StatusChangedCause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime StatusChangedDate {
            get {
                return this.StatusChangedDateField;
            }
            set {
                if ((this.StatusChangedDateField.Equals(value) != true)) {
                    this.StatusChangedDateField = value;
                    this.RaisePropertyChanged("StatusChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StatusChangedUser {
            get {
                return this.StatusChangedUserField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusChangedUserField, value) != true)) {
                    this.StatusChangedUserField = value;
                    this.RaisePropertyChanged("StatusChangedUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Storage {
            get {
                return this.StorageField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageField, value) != true)) {
                    this.StorageField = value;
                    this.RaisePropertyChanged("Storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Store {
            get {
                return this.StoreField;
            }
            set {
                if ((this.StoreField.Equals(value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TableOfContents {
            get {
                return this.TableOfContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.TableOfContentsField, value) != true)) {
                    this.TableOfContentsField = value;
                    this.RaisePropertyChanged("TableOfContents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string[] TargetAudiencesIds {
            get {
                return this.TargetAudiencesIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetAudiencesIdsField, value) != true)) {
                    this.TargetAudiencesIdsField = value;
                    this.RaisePropertyChanged("TargetAudiencesIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Transport {
            get {
                return this.TransportField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportField, value) != true)) {
                    this.TransportField = value;
                    this.RaisePropertyChanged("Transport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TypePrefix {
            get {
                return this.TypePrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.TypePrefixField, value) != true)) {
                    this.TypePrefixField = value;
                    this.RaisePropertyChanged("TypePrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UpdatedUserId {
            get {
                return this.UpdatedUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedUserIdField, value) != true)) {
                    this.UpdatedUserIdField = value;
                    this.RaisePropertyChanged("UpdatedUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorField, value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string VendorCode {
            get {
                return this.VendorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorCodeField, value) != true)) {
                    this.VendorCodeField = value;
                    this.RaisePropertyChanged("VendorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string WorldRegion {
            get {
                return this.WorldRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.WorldRegionField, value) != true)) {
                    this.WorldRegionField = value;
                    this.RaisePropertyChanged("WorldRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductAvailabilityStatuses", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Enti" +
        "ties")]
    internal enum ProductAvailabilityStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CategoryIsNotActive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartnerIsNotActive = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductIsNotActive = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CategoryPermissionNotFound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryRateNotFound = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TargetAudienceNotFound = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModerationNotApplied = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PriceNotFound = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductModerationStatuses", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Enti" +
        "ties")]
    internal enum ProductModerationStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InModeration = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Applied = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductParam", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Enti" +
        "ties")]
    [System.SerializableAttribute()]
    internal partial class ProductParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductStatuses", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Enti" +
        "ties")]
    internal enum ProductStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotActive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBasketParameters", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.ProductCatalog.API.Inpu" +
        "tParameters")]
    [System.SerializableAttribute()]
    internal partial class GetBasketParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CalcTotalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ClientContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountToSkipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountToTakeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> CalcTotalCount {
            get {
                return this.CalcTotalCountField;
            }
            set {
                if ((this.CalcTotalCountField.Equals(value) != true)) {
                    this.CalcTotalCountField = value;
                    this.RaisePropertyChanged("CalcTotalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.Dictionary<string, string> ClientContext {
            get {
                return this.ClientContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientContextField, value) != true)) {
                    this.ClientContextField = value;
                    this.RaisePropertyChanged("ClientContext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> CountToSkip {
            get {
                return this.CountToSkipField;
            }
            set {
                if ((this.CountToSkipField.Equals(value) != true)) {
                    this.CountToSkipField = value;
                    this.RaisePropertyChanged("CountToSkip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> CountToTake {
            get {
                return this.CountToTakeField;
            }
            set {
                if ((this.CountToTakeField.Equals(value) != true)) {
                    this.CountToTakeField = value;
                    this.RaisePropertyChanged("CountToTake");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductCatalogBasketService.IBasketService")]
    internal interface IBasketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportService/Echo", ReplyAction="http://tempuri.org/ISupportService/EchoResponse")]
        string Echo(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportService/Echo", ReplyAction="http://tempuri.org/ISupportService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/Add", ReplyAction="http://tempuri.org/IBasketService/AddResponse")]
        Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult Add(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/Add", ReplyAction="http://tempuri.org/IBasketService/AddResponse")]
        System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult> AddAsync(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/SetQuantity", ReplyAction="http://tempuri.org/IBasketService/SetQuantityResponse")]
        Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult SetQuantity(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/SetQuantity", ReplyAction="http://tempuri.org/IBasketService/SetQuantityResponse")]
        System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult> SetQuantityAsync(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/Remove", ReplyAction="http://tempuri.org/IBasketService/RemoveResponse")]
        Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult Remove(string clientId, string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/Remove", ReplyAction="http://tempuri.org/IBasketService/RemoveResponse")]
        System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult> RemoveAsync(string clientId, string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/GetBasketItem", ReplyAction="http://tempuri.org/IBasketService/GetBasketItemResponse")]
        Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemResult GetBasketItem(string clientId, string productId, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/GetBasketItem", ReplyAction="http://tempuri.org/IBasketService/GetBasketItemResponse")]
        System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemResult> GetBasketItemAsync(string clientId, string productId, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/GetBasketItems", ReplyAction="http://tempuri.org/IBasketService/GetBasketItemsResponse")]
        Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemsResult GetBasketItems(string clientId, string[] productIds, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/GetBasketItems", ReplyAction="http://tempuri.org/IBasketService/GetBasketItemsResponse")]
        System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemsResult> GetBasketItemsAsync(string clientId, string[] productIds, System.Collections.Generic.Dictionary<string, string> clientContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/GetBasket", ReplyAction="http://tempuri.org/IBasketService/GetBasketResponse")]
        Vtb24.Site.Services.ProductCatalogBasketService.BasketResult GetBasket(Vtb24.Site.Services.ProductCatalogBasketService.GetBasketParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasketService/GetBasket", ReplyAction="http://tempuri.org/IBasketService/GetBasketResponse")]
        System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketResult> GetBasketAsync(Vtb24.Site.Services.ProductCatalogBasketService.GetBasketParameters parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IBasketServiceChannel : Vtb24.Site.Services.ProductCatalogBasketService.IBasketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class BasketServiceClient : System.ServiceModel.ClientBase<Vtb24.Site.Services.ProductCatalogBasketService.IBasketService>, Vtb24.Site.Services.ProductCatalogBasketService.IBasketService {
        
        public BasketServiceClient() {
        }
        
        public BasketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string message) {
            return base.Channel.Echo(message);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string message) {
            return base.Channel.EchoAsync(message);
        }
        
        public Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult Add(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.Add(clientId, productId, quantity, clientContext);
        }
        
        public System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult> AddAsync(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.AddAsync(clientId, productId, quantity, clientContext);
        }
        
        public Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult SetQuantity(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.SetQuantity(clientId, productId, quantity, clientContext);
        }
        
        public System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult> SetQuantityAsync(string clientId, string productId, int quantity, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.SetQuantityAsync(clientId, productId, quantity, clientContext);
        }
        
        public Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult Remove(string clientId, string productId) {
            return base.Channel.Remove(clientId, productId);
        }
        
        public System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketManageResult> RemoveAsync(string clientId, string productId) {
            return base.Channel.RemoveAsync(clientId, productId);
        }
        
        public Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemResult GetBasketItem(string clientId, string productId, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.GetBasketItem(clientId, productId, clientContext);
        }
        
        public System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemResult> GetBasketItemAsync(string clientId, string productId, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.GetBasketItemAsync(clientId, productId, clientContext);
        }
        
        public Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemsResult GetBasketItems(string clientId, string[] productIds, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.GetBasketItems(clientId, productIds, clientContext);
        }
        
        public System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.GetBasketItemsResult> GetBasketItemsAsync(string clientId, string[] productIds, System.Collections.Generic.Dictionary<string, string> clientContext) {
            return base.Channel.GetBasketItemsAsync(clientId, productIds, clientContext);
        }
        
        public Vtb24.Site.Services.ProductCatalogBasketService.BasketResult GetBasket(Vtb24.Site.Services.ProductCatalogBasketService.GetBasketParameters parameters) {
            return base.Channel.GetBasket(parameters);
        }
        
        public System.Threading.Tasks.Task<Vtb24.Site.Services.ProductCatalogBasketService.BasketResult> GetBasketAsync(Vtb24.Site.Services.ProductCatalogBasketService.GetBasketParameters parameters) {
            return base.Channel.GetBasketAsync(parameters);
        }
    }
}
