// <auto-generated />
namespace Vtb24.Site.Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Security_Password_Otp_Antispoof : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Security_Password_Otp_Antispoof));
        
        string IMigrationMetadata.Id
        {
            get { return "201305292018352_Security_Password_Otp_Antispoof"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
