// <auto-generated />
namespace Vtb24.Site.Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SecurityInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecurityInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201305291453554_Security_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
