// <auto-generated />
namespace Vtb24.Site.Content.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Advertisements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Advertisements));
        
        string IMigrationMetadata.Id
        {
            get { return "201502051437310_Advertisements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
