// <auto-generated />
namespace Vtb24.Site.Content.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PageScript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageScript));
        
        string IMigrationMetadata.Id
        {
            get { return "201307111306445_PageScript"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
