// <auto-generated />
namespace Vtb24.Site.Content.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MyPointImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyPointImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201404040933310_MyPointImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
