CREATE UNIQUE NONCLUSTERED INDEX IX_BasketItems ON prod.BasketItems
	(
	ClientId,
	ProductId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE prod.BasketItems SET (LOCK_ESCALATION = TABLE)
GO