//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accrual
    {
        public int Id { get; set; }
        public System.Guid ReceiveEtlSessionId { get; set; }
        public Nullable<System.Guid> SendEtlSessionId { get; set; }
        public string ClientId { get; set; }
        public string BonusSum { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> BonusOperationDateTime { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime InsertedDate { get; set; }
    }
}
