//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    
    public enum AssignClientTargetAudienceStatus : int
    {
        Success = 1,
        TargetAudienceNotFound = 2,
        ClientNotFound = 3
    }
}
