//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankOffer
    {
        public string Id { get; set; }
        public string Description { get; set; }
        public decimal BonusCost { get; set; }
        public string ProductId { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string ClientId { get; set; }
        public string CardLast4Digits { get; set; }
        public BankOfferStatus Status { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string OfferId { get; set; }
    }
}
