//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientForDeletionResponse
    {
        public System.Guid EtlSessionId { get; set; }
        public string ClientId { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> DetachStatus { get; set; }
        public int Id { get; set; }
        public string Message { get; set; }
    }
}
