//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.VTB24.BankConnector.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaymentResponse2
    {
        public System.Guid EtlSessionId { get; set; }
        public int OrderId { get; set; }
        public int ItemPaymentStatus { get; set; }
        public int DeliveryPaymentStatus { get; set; }
        public Nullable<int> BonusGatewayStatus { get; set; }
        public string Message { get; set; }
    }
}
