DELETE FROM [prod].[OrderStatusWorkFlow]

INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (0, 5)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (0, 10)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (5, 10)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (10, 20)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (10, 30)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (10, 40)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (10, 50)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (10, 51)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (30, 40)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (30, 50)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (30, 51)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (30, 60)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (40, 50)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (40, 51)
INSERT INTO [prod].[OrderStatusWorkFlow] ([FromStatus], [ToStatus])
VALUES (40, 60)
