//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FixBasketItemPriceParam", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class FixBasketItemPriceParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasketItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfferIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfferNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasketItemId {
            get {
                return this.BasketItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BasketItemIdField, value) != true)) {
                    this.BasketItemIdField = value;
                    this.RaisePropertyChanged("BasketItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfferId {
            get {
                return this.OfferIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferIdField, value) != true)) {
                    this.OfferIdField = value;
                    this.RaisePropertyChanged("OfferId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfferName {
            get {
                return this.OfferNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferNameField, value) != true)) {
                    this.OfferNameField = value;
                    this.RaisePropertyChanged("OfferName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBase", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CheckOrderResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CommitOrderResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceResult))]
    public partial class ResultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDescription {
            get {
                return this.ResultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDescriptionField, value) != true)) {
                    this.ResultDescriptionField = value;
                    this.RaisePropertyChanged("ResultDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckOrderResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class CheckOrderResult : RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Checked {
            get {
                return this.CheckedField;
            }
            set {
                if ((this.CheckedField.Equals(value) != true)) {
                    this.CheckedField = value;
                    this.RaisePropertyChanged("Checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode {
            get {
                return this.ReasonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonCodeField, value) != true)) {
                    this.ReasonCodeField = value;
                    this.RaisePropertyChanged("ReasonCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommitOrderResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class CommitOrderResult : RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ConfirmedStatuses ConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ConfirmedStatuses Confirmed {
            get {
                return this.ConfirmedField;
            }
            set {
                if ((this.ConfirmedField.Equals(value) != true)) {
                    this.ConfirmedField = value;
                    this.RaisePropertyChanged("Confirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalOrderId {
            get {
                return this.InternalOrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalOrderIdField, value) != true)) {
                    this.InternalOrderIdField = value;
                    this.RaisePropertyChanged("InternalOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode {
            get {
                return this.ReasonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonCodeField, value) != true)) {
                    this.ReasonCodeField = value;
                    this.RaisePropertyChanged("ReasonCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeliveryVariantsResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class GetDeliveryVariantsResult : RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryGroup[] DeliveryGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.VariantsLocation LocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryGroup[] DeliveryGroups {
            get {
                return this.DeliveryGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryGroupsField, value) != true)) {
                    this.DeliveryGroupsField = value;
                    this.RaisePropertyChanged("DeliveryGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.VariantsLocation Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FixBasketItemPriceResult", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class FixBasketItemPriceResult : RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ActualPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UtcDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ActualPrice {
            get {
                return this.ActualPriceField;
            }
            set {
                if ((this.ActualPriceField.Equals(value) != true)) {
                    this.ActualPriceField = value;
                    this.RaisePropertyChanged("ActualPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Confirmed {
            get {
                return this.ConfirmedField;
            }
            set {
                if ((this.ConfirmedField.Equals(value) != true)) {
                    this.ConfirmedField = value;
                    this.RaisePropertyChanged("Confirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode {
            get {
                return this.ReasonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonCodeField, value) != true)) {
                    this.ReasonCodeField = value;
                    this.RaisePropertyChanged("ReasonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UtcDateTime {
            get {
                return this.UtcDateTimeField;
            }
            set {
                if ((this.UtcDateTimeField.Equals(value) != true)) {
                    this.UtcDateTimeField = value;
                    this.RaisePropertyChanged("UtcDateTime");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmedStatuses", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    public enum ConfirmedStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Committed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddToQueue = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VariantsLocation", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class VariantsLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalLocationId {
            get {
                return this.ExternalLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalLocationIdField, value) != true)) {
                    this.ExternalLocationIdField = value;
                    this.RaisePropertyChanged("ExternalLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KladrCode {
            get {
                return this.KladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KladrCodeField, value) != true)) {
                    this.KladrCodeField = value;
                    this.RaisePropertyChanged("KladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryGroup", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryVariant[] DeliveryVariantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryVariant[] DeliveryVariants {
            get {
                return this.DeliveryVariantsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryVariantsField, value) != true)) {
                    this.DeliveryVariantsField = value;
                    this.RaisePropertyChanged("DeliveryVariants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryVariant", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryVariant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DeliveryCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryVariantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalDeliveryVariantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemsCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.PickupPoint[] PickupPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalCostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DeliveryCost {
            get {
                return this.DeliveryCostField;
            }
            set {
                if ((this.DeliveryCostField.Equals(value) != true)) {
                    this.DeliveryCostField = value;
                    this.RaisePropertyChanged("DeliveryCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryVariantName {
            get {
                return this.DeliveryVariantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryVariantNameField, value) != true)) {
                    this.DeliveryVariantNameField = value;
                    this.RaisePropertyChanged("DeliveryVariantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDeliveryVariantId {
            get {
                return this.ExternalDeliveryVariantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalDeliveryVariantIdField, value) != true)) {
                    this.ExternalDeliveryVariantIdField = value;
                    this.RaisePropertyChanged("ExternalDeliveryVariantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemsCost {
            get {
                return this.ItemsCostField;
            }
            set {
                if ((this.ItemsCostField.Equals(value) != true)) {
                    this.ItemsCostField = value;
                    this.RaisePropertyChanged("ItemsCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.PickupPoint[] PickupPoints {
            get {
                return this.PickupPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupPointsField, value) != true)) {
                    this.PickupPointsField = value;
                    this.RaisePropertyChanged("PickupPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PickupPoint", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class PickupPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DeliveryCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryVariantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalDeliveryVariantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalPickupPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemsCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] OperatingHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PhonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalCostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DeliveryCost {
            get {
                return this.DeliveryCostField;
            }
            set {
                if ((this.DeliveryCostField.Equals(value) != true)) {
                    this.DeliveryCostField = value;
                    this.RaisePropertyChanged("DeliveryCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryVariantName {
            get {
                return this.DeliveryVariantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryVariantNameField, value) != true)) {
                    this.DeliveryVariantNameField = value;
                    this.RaisePropertyChanged("DeliveryVariantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDeliveryVariantId {
            get {
                return this.ExternalDeliveryVariantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalDeliveryVariantIdField, value) != true)) {
                    this.ExternalDeliveryVariantIdField = value;
                    this.RaisePropertyChanged("ExternalDeliveryVariantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalPickupPointId {
            get {
                return this.ExternalPickupPointIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalPickupPointIdField, value) != true)) {
                    this.ExternalPickupPointIdField = value;
                    this.RaisePropertyChanged("ExternalPickupPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemsCost {
            get {
                return this.ItemsCostField;
            }
            set {
                if ((this.ItemsCostField.Equals(value) != true)) {
                    this.ItemsCostField = value;
                    this.RaisePropertyChanged("ItemsCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] OperatingHours {
            get {
                return this.OperatingHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatingHoursField, value) != true)) {
                    this.OperatingHoursField = value;
                    this.RaisePropertyChanged("OperatingHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Phones {
            get {
                return this.PhonesField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonesField, value) != true)) {
                    this.PhonesField = value;
                    this.RaisePropertyChanged("Phones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BonusDeliveryCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BonusItemsCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BonusTotalCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DeliveryCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryInfo DeliveryInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalOrderStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalOrderStatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsertedUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.OrderItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemsCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.OrderStatuses StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusChangedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusDeliveryCost {
            get {
                return this.BonusDeliveryCostField;
            }
            set {
                if ((this.BonusDeliveryCostField.Equals(value) != true)) {
                    this.BonusDeliveryCostField = value;
                    this.RaisePropertyChanged("BonusDeliveryCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusItemsCost {
            get {
                return this.BonusItemsCostField;
            }
            set {
                if ((this.BonusItemsCostField.Equals(value) != true)) {
                    this.BonusItemsCostField = value;
                    this.RaisePropertyChanged("BonusItemsCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusTotalCost {
            get {
                return this.BonusTotalCostField;
            }
            set {
                if ((this.BonusTotalCostField.Equals(value) != true)) {
                    this.BonusTotalCostField = value;
                    this.RaisePropertyChanged("BonusTotalCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DeliveryCost {
            get {
                return this.DeliveryCostField;
            }
            set {
                if ((this.DeliveryCostField.Equals(value) != true)) {
                    this.DeliveryCostField = value;
                    this.RaisePropertyChanged("DeliveryCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryInfo DeliveryInfo {
            get {
                return this.DeliveryInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryInfoField, value) != true)) {
                    this.DeliveryInfoField = value;
                    this.RaisePropertyChanged("DeliveryInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalOrderId {
            get {
                return this.ExternalOrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalOrderIdField, value) != true)) {
                    this.ExternalOrderIdField = value;
                    this.RaisePropertyChanged("ExternalOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalOrderStatusCode {
            get {
                return this.ExternalOrderStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalOrderStatusCodeField, value) != true)) {
                    this.ExternalOrderStatusCodeField = value;
                    this.RaisePropertyChanged("ExternalOrderStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalOrderStatusDescription {
            get {
                return this.ExternalOrderStatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalOrderStatusDescriptionField, value) != true)) {
                    this.ExternalOrderStatusDescriptionField = value;
                    this.RaisePropertyChanged("ExternalOrderStatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedDate {
            get {
                return this.InsertedDateField;
            }
            set {
                if ((this.InsertedDateField.Equals(value) != true)) {
                    this.InsertedDateField = value;
                    this.RaisePropertyChanged("InsertedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertedUserId {
            get {
                return this.InsertedUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InsertedUserIdField, value) != true)) {
                    this.InsertedUserIdField = value;
                    this.RaisePropertyChanged("InsertedUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.OrderItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemsCost {
            get {
                return this.ItemsCostField;
            }
            set {
                if ((this.ItemsCostField.Equals(value) != true)) {
                    this.ItemsCostField = value;
                    this.RaisePropertyChanged("ItemsCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.OrderStatuses Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusChangedDate {
            get {
                return this.StatusChangedDateField;
            }
            set {
                if ((this.StatusChangedDateField.Equals(value) != true)) {
                    this.StatusChangedDateField = value;
                    this.RaisePropertyChanged("StatusChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalWeight {
            get {
                return this.TotalWeightField;
            }
            set {
                if ((this.TotalWeightField.Equals(value) != true)) {
                    this.TotalWeightField = value;
                    this.RaisePropertyChanged("TotalWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedUserId {
            get {
                return this.UpdatedUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedUserIdField, value) != true)) {
                    this.UpdatedUserIdField = value;
                    this.RaisePropertyChanged("UpdatedUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryInfo", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryAddress AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Contact ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryTypes DeliveryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryVariantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.VariantsLocation DeliveryVariantsLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalDeliveryVariantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.PickupPoint PickupPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddText {
            get {
                return this.AddTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AddTextField, value) != true)) {
                    this.AddTextField = value;
                    this.RaisePropertyChanged("AddText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryAddress Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Contact Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.DeliveryTypes DeliveryType {
            get {
                return this.DeliveryTypeField;
            }
            set {
                if ((this.DeliveryTypeField.Equals(value) != true)) {
                    this.DeliveryTypeField = value;
                    this.RaisePropertyChanged("DeliveryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryVariantName {
            get {
                return this.DeliveryVariantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryVariantNameField, value) != true)) {
                    this.DeliveryVariantNameField = value;
                    this.RaisePropertyChanged("DeliveryVariantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.VariantsLocation DeliveryVariantsLocation {
            get {
                return this.DeliveryVariantsLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryVariantsLocationField, value) != true)) {
                    this.DeliveryVariantsLocationField = value;
                    this.RaisePropertyChanged("DeliveryVariantsLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDeliveryVariantId {
            get {
                return this.ExternalDeliveryVariantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalDeliveryVariantIdField, value) != true)) {
                    this.ExternalDeliveryVariantIdField = value;
                    this.RaisePropertyChanged("ExternalDeliveryVariantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.PickupPoint PickupPoint {
            get {
                return this.PickupPointField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupPointField, value) != true)) {
                    this.PickupPointField = value;
                    this.RaisePropertyChanged("PickupPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasketItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfferIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfferNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasketItemId {
            get {
                return this.BasketItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BasketItemIdField, value) != true)) {
                    this.BasketItemIdField = value;
                    this.RaisePropertyChanged("BasketItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfferId {
            get {
                return this.OfferIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferIdField, value) != true)) {
                    this.OfferIdField = value;
                    this.RaisePropertyChanged("OfferId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfferName {
            get {
                return this.OfferNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferNameField, value) != true)) {
                    this.OfferNameField = value;
                    this.RaisePropertyChanged("OfferName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatuses", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    public enum OrderStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registration = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelledByPartner = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryWaiting = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveredWithDelay = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDelivered = 60,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryAddress", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityKladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictKladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionKladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownKladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressText {
            get {
                return this.AddressTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTextField, value) != true)) {
                    this.AddressTextField = value;
                    this.RaisePropertyChanged("AddressText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityKladrCode {
            get {
                return this.CityKladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityKladrCodeField, value) != true)) {
                    this.CityKladrCodeField = value;
                    this.RaisePropertyChanged("CityKladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityTitle {
            get {
                return this.CityTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CityTitleField, value) != true)) {
                    this.CityTitleField = value;
                    this.RaisePropertyChanged("CityTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictKladrCode {
            get {
                return this.DistrictKladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictKladrCodeField, value) != true)) {
                    this.DistrictKladrCodeField = value;
                    this.RaisePropertyChanged("DistrictKladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictTitle {
            get {
                return this.DistrictTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictTitleField, value) != true)) {
                    this.DistrictTitleField = value;
                    this.RaisePropertyChanged("DistrictTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flat {
            get {
                return this.FlatField;
            }
            set {
                if ((object.ReferenceEquals(this.FlatField, value) != true)) {
                    this.FlatField = value;
                    this.RaisePropertyChanged("Flat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string House {
            get {
                return this.HouseField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseField, value) != true)) {
                    this.HouseField = value;
                    this.RaisePropertyChanged("House");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionKladrCode {
            get {
                return this.RegionKladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionKladrCodeField, value) != true)) {
                    this.RegionKladrCodeField = value;
                    this.RaisePropertyChanged("RegionKladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionTitle {
            get {
                return this.RegionTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionTitleField, value) != true)) {
                    this.RegionTitleField = value;
                    this.RaisePropertyChanged("RegionTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetTitle {
            get {
                return this.StreetTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetTitleField, value) != true)) {
                    this.StreetTitleField = value;
                    this.RaisePropertyChanged("StreetTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownKladrCode {
            get {
                return this.TownKladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TownKladrCodeField, value) != true)) {
                    this.TownKladrCodeField = value;
                    this.RaisePropertyChanged("TownKladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownTitle {
            get {
                return this.TownTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TownTitleField, value) != true)) {
                    this.TownTitleField = value;
                    this.RaisePropertyChanged("TownTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryTypes", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    public enum DeliveryTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pickup = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeliveryVariantsParam", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class GetDeliveryVariantsParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.OrderItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.OrderItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/RapidSoft.Loaylty.PartnersConnector.Inter" +
        "faces.Entities")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KladrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalLocationId {
            get {
                return this.ExternalLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalLocationIdField, value) != true)) {
                    this.ExternalLocationIdField = value;
                    this.RaisePropertyChanged("ExternalLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KladrCode {
            get {
                return this.KladrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KladrCodeField, value) != true)) {
                    this.KladrCodeField = value;
                    this.RaisePropertyChanged("KladrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartnersOrderManagementService.IOrderManagementService")]
    public interface IOrderManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportService/Echo", ReplyAction="http://tempuri.org/ISupportService/EchoResponse")]
        string Echo(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportService/Echo", ReplyAction="http://tempuri.org/ISupportService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/FixBasketItemPrice", ReplyAction="http://tempuri.org/IOrderManagementService/FixBasketItemPriceResponse")]
        RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceResult FixBasketItemPrice(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/FixBasketItemPrice", ReplyAction="http://tempuri.org/IOrderManagementService/FixBasketItemPriceResponse")]
        System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceResult> FixBasketItemPriceAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/CheckOrder", ReplyAction="http://tempuri.org/IOrderManagementService/CheckOrderResponse")]
        RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CheckOrderResult CheckOrder(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/CheckOrder", ReplyAction="http://tempuri.org/IOrderManagementService/CheckOrderResponse")]
        System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CheckOrderResult> CheckOrderAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/CommitOrder", ReplyAction="http://tempuri.org/IOrderManagementService/CommitOrderResponse")]
        RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CommitOrderResult CommitOrder(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/CommitOrder", ReplyAction="http://tempuri.org/IOrderManagementService/CommitOrderResponse")]
        System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CommitOrderResult> CommitOrderAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/CustomCommitOrder", ReplyAction="http://tempuri.org/IOrderManagementService/CustomCommitOrderResponse")]
        RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase CustomCommitOrder(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order, string methodName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/CustomCommitOrder", ReplyAction="http://tempuri.org/IOrderManagementService/CustomCommitOrderResponse")]
        System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase> CustomCommitOrderAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order, string methodName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/GetDeliveryVariants", ReplyAction="http://tempuri.org/IOrderManagementService/GetDeliveryVariantsResponse")]
        RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsResult GetDeliveryVariants(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManagementService/GetDeliveryVariants", ReplyAction="http://tempuri.org/IOrderManagementService/GetDeliveryVariantsResponse")]
        System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsResult> GetDeliveryVariantsAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsParam param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderManagementServiceChannel : RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.IOrderManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderManagementServiceClient : System.ServiceModel.ClientBase<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.IOrderManagementService>, RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.IOrderManagementService {
        
        public OrderManagementServiceClient() {
        }
        
        public OrderManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string message) {
            return base.Channel.Echo(message);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string message) {
            return base.Channel.EchoAsync(message);
        }
        
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceResult FixBasketItemPrice(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceParam param) {
            return base.Channel.FixBasketItemPrice(param);
        }
        
        public System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceResult> FixBasketItemPriceAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.FixBasketItemPriceParam param) {
            return base.Channel.FixBasketItemPriceAsync(param);
        }
        
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CheckOrderResult CheckOrder(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order) {
            return base.Channel.CheckOrder(order);
        }
        
        public System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CheckOrderResult> CheckOrderAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order) {
            return base.Channel.CheckOrderAsync(order);
        }
        
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CommitOrderResult CommitOrder(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order) {
            return base.Channel.CommitOrder(order);
        }
        
        public System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.CommitOrderResult> CommitOrderAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order) {
            return base.Channel.CommitOrderAsync(order);
        }
        
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase CustomCommitOrder(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order, string methodName) {
            return base.Channel.CustomCommitOrder(order, methodName);
        }
        
        public System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.ResultBase> CustomCommitOrderAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.Order order, string methodName) {
            return base.Channel.CustomCommitOrderAsync(order, methodName);
        }
        
        public RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsResult GetDeliveryVariants(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsParam param) {
            return base.Channel.GetDeliveryVariants(param);
        }
        
        public System.Threading.Tasks.Task<RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsResult> GetDeliveryVariantsAsync(RapidSoft.Loaylty.PartnersConnector.WsClients.PartnersOrderManagementService.GetDeliveryVariantsParam param) {
            return base.Channel.GetDeliveryVariantsAsync(param);
        }
    }
}
